### ISSUE TITLE
[ feature request ] Delete and rewrite post

### ISSUE THREAD

**Issue by smonff** [tuskyapp/Tusky#1073] opened 2019-02-23 11:50 UTC
In web interface, there is a useful feature, called *Delete and rewrite* that makes possible to delete a toot, and immediately open an edit field containing the previously deleted toot: this actually delete it from timelines, but it is a kind of *edit* feature, mostly useful when you made some typo after posting something.

This is only *my* experience, but I would say that I use it more than 10% of the times when I toot, so, quite useful IMO.

This is implemented in Mastalab. I used it during 6 months and recently switched to Tusky, that's why I think it is a feature that is missing in Tusky.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Thanks

**Comment by charlag** [comment] 2019-02-25 17:29
Duplicate of #705

**Closed by charlag** 2019-02-25 17:29 UTC
