### ISSUE TITLE
Upload of photos fails

### ISSUE THREAD

**Issue by chloeboulez** [tuskyapp/Tusky#1197] opened 2019-04-17 13:22 UTC
Upload of photo fails

* * * *
- Tusky Version: 6.1
- Android Version: 9
- Android Device: note 8
- Mastodon instance (if applicable): switter.at

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nyex** [comment] 2019-04-25 12:12
I'm having the same issue, I think. The app crashes when I pick a photo to upload.

It only happens on my phone (Moto G4 Play with LineageOS 14, rooted) and *not* on my tablet (Sony Xperia Z3 compact, Lineage 15, rooted). Both are running Tusky 6.1 from the Play Store.

**Comment by charlag** [comment] 2019-04-27 11:51
I think that crashing when uploading a photo and failing to upload are two different things.
We need more info here, does it happen always or sometimes, do you have VPN on, what's your network conditions and so on.

**Comment by nyex** [comment] 2019-04-27 11:56
that makes sense, yes. i wasn't sure what 'fail' meant in this case, which is why i commented.

in my case though, the crash only happens in one device and not with another, so it's definitely not a network issue. i'm not so sure how to go about debugging it, but i'm willing to help with what i can.

should i open a new issue?

**Comment by charlag** [comment] 2019-04-27 11:58
@nyex sorry for being unclear, my question wasn't addressed to you.
Yes, please, open another issue. The best help would be to just get a stacktrace using adb.

**Comment by RX14** [comment] 2019-06-07 20:05
I'm getting this error, pleroma logs say

```
[error] Internal server error: %Plug.Parsers.ParseError{exception: %RuntimeError{message: "invalid multipart, body terminated too soon"}, plug_status: 400}
```

error happens at the completion of upload: "the upload failed"

**Comment by connyduck** [comment] 2019-06-07 20:27
Can you all please try out the current nightly? There was a PR merged that possibly fixes this problem 
https://github.com/tuskyapp/Tusky/pull/1294

**Comment by RX14** [comment] 2019-06-13 01:55
Can't reproduce any more :(

Weird

**Comment by Wirehead9** [comment] 2020-07-28 17:40
I'm having the same issue, maybe trelated to the image size. I've tried some pictures with less than 1Mb and the yare working, some over 10Mb are not getting uploaded.

- Tusky Version: 11.0 (installed from F-Droid)

Android Version: 7.1.2 (/e/ OS)

Android Device: Redmi Note 4 (mido)

Mastodon instance (if applicable): mastodon.uno

It works fine if i use the nightly build (always from F-Droid)

**Comment by connyduck** [comment] 2020-07-28 17:46
https://github.com/tuskyapp/Tusky/pull/1800

**Closed by connyduck** 2020-07-28 17:46 UTC
