### ISSUE TITLE
[Feature Request] Time of boost

### ISSUE THREAD

**Issue by ratcatcher** [tuskyapp/Tusky#3073] opened 2022-12-19 13:28 UTC
When a boosted feed appears in a timeline, the timestamp is that of the original toot making it appear that toots are out of chronological order.

Would it be possible to include the timestamp for when the post was boosted, too?

Similarly for edited posts: would it be possible to include the timestamp of the most recent edit?

I realise that these stamps are already flagged with * but the additional information would add clarity.

* * * *
- Tusky Version:  20.0-6aed1c68
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2023-01-02 12:17
You can go to the status details to see the time of the last edit.

Timestamps of boosts is duplicate of https://github.com/tuskyapp/Tusky/issues/2808

**Closed by connyduck** 2023-01-02 12:17 UTC
