### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by stefanstranger** [tuskyapp/Tusky#3115] opened 2022-12-28 17:03 UTC
I'm rather new to Mastodon and Tusky is one of the first Android clients I'm currently using. So far it has been a very good experience. 

But some of the Toots are in a language I'm less fluent in. Would it be possible to have a translate Toot option within the Tusky client? 🙏

Regards 
Stefan 

* * * *
- Tusky Version: 20.0
- Android Version: 11
- Android Device: OnePlus7 
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2022-12-28 21:02
Duplicate of #2188

**Closed by Tak** 2022-12-28 21:02 UTC
