### ISSUE TITLE
Push notifications being sent after notifications are viewed on another device.

### ISSUE THREAD

**Issue by TimMad42** [tuskyapp/Tusky#1579] opened 2019-12-04 20:19 UTC
When using mastodon on PC I still get push notifications from tusky for notifications I have viewed and even replied to on the computer. This is often a lot of notifications so my phone will go off numerous times about notifications I had looked at several minutes prior. The push notifications seem to be delayed by 7-15 minutes from the actual notification as well, so I will continue to get push notifications for 10 or so minutes after a conversation has been seen, replied to, and concluded.

* * * *
- Tusky Version: 9.1
- Android Version:
- Android Device: Galaxy S7
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-12-04 20:39
Hi
I think it's a duplicate of #1542 
Pls tell me if I'm wrong

**Closed by charlag** 2019-12-04 20:39 UTC

**Comment by TimMad42** [comment] 2019-12-04 21:10
Ah my bad I had missed that one.
