### ISSUE TITLE
Feature: Support admin/moderation tasks

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3059] opened 2022-12-17 12:00 UTC
[Note: no idea what this would entail, I'm just recording the feature request]

@rperez@c.im, in https://c.im/@rperez/109516649904089302
> @Lmck @USelaine @asonix I'm sorry to hear that. After trying #Tooot and #Tusky, I decided to stick with Tusky. I still haven't found a single #native mobile app with admin and moderation capabilities though. Guess we'll have to stick to the #browser for that, for now.

* * * *
- Tusky Version: 20

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2022-12-17 17:09
Duplicate of #1341

**Closed by Tak** 2022-12-17 17:09 UTC
