### ISSUE TITLE
Double layered text

### ISSUE THREAD

**Issue by mal0ki** [tuskyapp/Tusky#2265] opened 2021-11-04 17:10 UTC
I tried searching for this issue, and I'm not 100% sure how to phrase it or what to search for. 

This seems to be an issue both on Nightly and latest release (unless I haven't successfully updated, wops), that occasionally when we pull down to update with new toots, we get a double layer of text.

This was reported to me by another user as well, thus the we, and the vague description, and no device info other than nightly.  

* * * *
- Tusky Version: Nightly / Current
- Android Version: -
- Android Device: -

**Comment by connyduck** [comment] 2022-03-13 16:16
Duplicate of https://github.com/tuskyapp/Tusky/issues/1122

**Closed by connyduck** 2022-03-13 16:16 UTC
