### ISSUE TITLE
Impossible to upload pictures as attachment

### ISSUE THREAD

**Issue by manuel-uberti** [tuskyapp/Tusky#174] opened 2017-04-16 13:34 UTC
Hi,

first of all thanks for Tusky.

I am using version `1.1.2` of Tusky on Android `6.0 MRA58K`, on a Xiaomi Redmi Note 4.

Whenever I try to attach a picture (both from the gallery and from the file manager), Tusky gives this message:

`That file could not be opened`.

If you need more details, please feel free to ask and I see what I can do.

**Comment by tchncs** [comment] 2017-04-16 13:37
Maybe tusky is lacking permission?

**Comment by manuel-uberti** [comment] 2017-04-16 13:39
Every permission available on my phone for Tusky is already enabled:

- Send MMS messages
- Access and change files on internal storage
- Show on lock screen
- Start in background

**Comment by Vavassor** [comment] 2017-04-16 22:25
It requests permission before opening the image picker, so the fact that it got past that and let you pick a photo seems to indicate that part is fine.

This error can appear in a couple of places. First it tries to look at the database entry to find out the file size (OpenableColumns.SIZE) and this failing would cause the error. Or after that, it opens the stream and makes a thumbnail to show as the preview image before it can be put in the upload queue proper. So the opening & thumbnail creation process failing would also lead to that error.

**Comment by manuel-uberti** [comment] 2017-04-17 06:42
Thanks for the explanation.

On the other hand, on my other phone (Fairphone, running Fairphone OS 1.13.0) latest Tusky works just fine. I was able to take a picture with my phone and toot it correcty (see: https://mastodon.social/@manuel_uberti/2623754).

**Comment by manuel-uberti** [comment] 2017-04-26 09:15
Since it seems to be related to the Redmi, is it ok if I close this one?

**Comment by rototom** [comment] 2017-10-27 23:10
Redmi 4 prime with same problem here.

**Comment by charlag** [comment] 2017-10-28 15:54
I think we will need to add (and collect) some logs, maybe special build will do.
I had problems with image uploading on Xiaomi devices before.

**Comment by charlag** [comment] 2017-11-11 08:15
@connyduck you've increased timeout - I guess this is fixed now?

**Comment by connyduck** [comment] 2017-11-11 09:13
I think these are two different problems. I fixed the one where Tusky could not upload a file. Here the problem is that the file can't even be opened.

**Comment by charlag** [comment] 2017-11-11 11:20
Ah, I see, sorry, I even commented about it, right

**Comment by manuel-uberti** [comment] 2018-03-11 16:01
Is this still an issue? I am not using Mastodon anymore, but I was just wondering if we can close this.

**Comment by manuel-uberti** [comment] 2018-03-11 16:01
Is this still an issue? I am not using Mastodon anymore, but I was just wondering if we can close this.

**Comment by charlag** [comment] 2018-03-11 19:17
Oh, sorry to hear that
I think so, heard no complains recently

**Closed by charlag** 2018-03-11 19:17 UTC
Labels: bug
