### ISSUE TITLE
Check who boost/favourite a toot and their profiles

### ISSUE THREAD

**Issue by alxlg** [tuskyapp/Tusky#933] opened 2018-11-28 13:16 UTC
I don't see a way to check who boosted or favourited a toot and look for their profiles.

When the toot is mine I receive a notification for each user that favourites or boosts it and still I can't see his/her profile.

I think that at least opening "single toot view" I should be able to tap somewhere to see a list of users that favourited the toot and be able to do the same to see the list of user who boosted.

Sorry if this is a duplicated issue but I was not able to find one about this.

**Comment by connyduck** [comment] 2018-11-28 18:57
duplicate of https://github.com/tuskyapp/Tusky/issues/455

**Closed by connyduck** 2018-11-28 18:57 UTC
Labels: duplicate
