### ISSUE TITLE
Feature Request - Mute video playback

### ISSUE THREAD

**Issue by egooner** [tuskyapp/Tusky#2840] opened 2022-11-16 07:24 UTC
Video playback, would be good to have an option to mute videos by default and unmute when playing optionally!!
Some videos do not need the sound but when watching in a crowded area it would be nice not to have to keep turning mobile volume down!

**Comment by thibaultmol** [comment] 2022-11-16 14:47
Is this a duplicate of
https://github.com/tuskyapp/Tusky/issues/2675
?

**Comment by egooner** [comment] 2022-11-16 14:51
Apologies - it is - I probably searched another issue before making this
one and neglected to search for this!

Thanks

Richard

**Closed** 2023-05-11 14:52 UTC
