### ISSUE TITLE
[ feature request ] Delete and rewrite post

### ISSUE THREAD

**Issue by smonff** [tuskyapp/Tusky#1072] opened 2019-02-23 10:03 UTC
In web interface, there is a useful feature, called *Delete and rewrite* that makes possible to delete a tooth, and immediately open an edit field continuing the previously deleted toot: this actually delete it, but it is a kind of *edit* feature, mostly useful when you made some typo after posting something.

This is only *my* experience, but I would say that I use it more than 10% of the times I toot, so, quite useful IMO.

This is implemented by Mastalab. I used it during 6 months and recently switched to Tusky, that's why I think it is a feature that is missing in Tusky.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Thanks 🖐️!

**Comment by connyduck** [comment] 2019-02-23 10:04
duplicate of #705

**Closed by connyduck** 2019-02-23 10:04 UTC
Labels: duplicate

**Comment by smonff** [comment] 2019-02-23 11:59
Sorry I searched badly :disappointed:
