### ISSUE TITLE
No way to edit image description on post edit

### ISSUE THREAD

**Issue by hrw** [tuskyapp/Tusky#3268] opened 2023-02-05 16:19 UTC
There is no way to add alt text to images while editing a post.

It is easy to forget about adding description to images. When I tried to edit post the only thing I could do with picture was removing it.

* * * *
- Tusky Version: 21.0
- Android Version: 10
- Android Device: Huawei P30
- Mastodon instance (if applicable): society.oftrolls.com 

- [y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2023-02-05 17:05
Duplicate of https://github.com/tuskyapp/Tusky/issues/3211

**Comment by Tak** [comment] 2023-02-05 20:32
As mentioned, this is a duplicate of #3211

**Closed by Tak** 2023-02-05 20:32 UTC
