### ISSUE TITLE
Bigger touch targets for toot actions

### ISSUE THREAD

**Issue by alexcg1** [tuskyapp/Tusky#2883] opened 2022-11-20 19:40 UTC
When I go to star, bookmark or whatever a toot, I often miss the button. Can you expand the torch target for them?

![Screenshot_20221120-203850_1.png](https://user-images.githubusercontent.com/4182659/202922415-8c9a5078-f553-4614-9cec-d502dd6efa8e.png) 

(the orange highlighted bits. Forgive me. My phone photo editor isn't ideal for this)

Many thanks! Loving your app ♥️

**Comment by charlag** [comment] 2022-11-20 21:03
Duplicate of #2883

**Comment by alexcg1** [comment] 2022-11-21 10:29
@charlag wait, this *is* #2883. It's a dup of itself? :sweat_smile:

**Comment by charlag** [comment] 2022-11-21 13:21
My bad, duplicate of #2825

**Closed by charlag** 2022-11-21 13:21 UTC
