### ISSUE TITLE
posts get stuck on screen

### ISSUE THREAD

**Issue by protodrew** [tuskyapp/Tusky#2277] opened 2021-12-13 21:03 UTC
Don't have screenshots rn but will get some next time it occurs. Sometimes posts get stuck in their position on the screen, so when you scroll up or down they don't move, and stay locked in place causing overlap with other posts. When you restart the app it is resolved, as far as I can tell there is no specific combination of things that causes it.
* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: Galaxy s20 ultra
- Mastodon instance (if applicable): n/a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2022-03-13 16:09
Duplicate of https://github.com/tuskyapp/Tusky/issues/2265

**Closed by connyduck** 2022-03-13 16:09 UTC

**Comment by connyduck** [comment] 2022-03-13 16:16
or rather https://github.com/tuskyapp/Tusky/issues/1122
