### ISSUE TITLE
Decrease threshold of vertical to horizontal swiping sensitivity 

### ISSUE THREAD

**Issue by Nacho-King** [tuskyapp/Tusky#2530] opened 2022-05-15 11:51 UTC
Currently I find that the vertical swiping action is often interpreted as a horizontal swipe, if your vertical swipe is not perfectly straight. Could this detection threshold be changed somehow? 

* * * *
- Tusky Version: 17.0
- Android Version: 12
- Android Device: Pixel 4a

- [ ✅ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2022-05-15 12:05
Hi
Duplicate of #2112

**Closed by charlag** 2022-05-15 12:05 UTC

**Comment by charlag** [comment] 2022-05-15 16:31
No worries
