### ISSUE TITLE
[Feature Request] Show client name of toots

### ISSUE THREAD

**Issue by frumble** [tuskyapp/Tusky#3266] opened 2023-02-05 00:02 UTC
I start to really miss a client info in toot view in Tusky which tells me about the author’s client. This info is always an elegant way to quickly sort people into Android/iOS/Linux/Mac platforms in technical (and sometimes ideological) discussions.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment] 2023-02-05 12:51
It does so. But only on the local timeline, if I see this correctly.

Is there some place where the web client (browser) shows it for you and Tusky doesn't?

**Comment by nikclayton** [comment] 2023-02-08 12:26
> It does so. But only on the local timeline, if I see this correctly.

It's in posts from the federated timeline as well (I just checked to confirm).

As far as I can tell, anywhere you can tap a status to get the detailed view (the one with the specific number of boosts, favourites, etc) it will also show you the client name.

*If* it was provided. As https://docs.joinmastodon.org/entities/Status/#application notes, this is an optional field, so a lot of the time it's not populated.

I think this can be closed as "working as intended".

**Closed** 2023-02-16 19:47 UTC
