### ISSUE TITLE
Image uploads started failing

### ISSUE THREAD

**Issue by ieure** [tuskyapp/Tusky#1754] opened 2020-04-14 20:24 UTC
After upgrading to Tusky 10 and Android 10, I can't upload images taken with my phone's camera.  I don't know which thing broke, but this was working in earlier versions of Tusky and Android.

This is a regression of #677, which I reported a couple years ago.  #1727 is possibly related as well.

1. Take a photo with the system's camera app.
2. Switch to Tusky, compose toot.
3. Tap attachment button.
4. Select the photo you just took.  In this case, the photo is shown as being 7.64mb.
5. Wait a little bit for the upload progress circle to close.
6. Receive "The upload failed" error.  The image vanishes from the compose toot screen.

* * * *
- Tusky Version: 10.0
- Android Version: 10, build number 52.1.A.0.618
- Android Device: Sony Xperia XZ2 Compact
- Mastodon instance (if applicable): mastodon.social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2020-04-14 20:29
Hi, thanks for reporting! We will hopefully be able to get more info once https://github.com/tuskyapp/Tusky/pull/1751 is merged

**Comment by kyori19** [comment] 2020-04-15 00:42
I have same issue on my phone (G8441, Android 8.0.0).

I can upload screenshots (approx. 100 ~ 300 KB) but can't upload photos taken with camera (approx. 3 ~ 6 MB) and server returns 422 (Unprocessable Entity) error.

Uploading same photos on WebUI works fine, so I think downsizing process has an issue.

**Comment by ieure** [comment] 2020-04-17 03:55
> Uploading same photos on WebUI works fine, so I think downsizing process has an issue.

I get a 422 if I upload the same photo to the web UI.  Maybe .social tightened their image size restrictions?

**Closed** 2020-05-21 12:50 UTC

**Comment by cb360** [comment] 2021-08-15 07:12
version:15.1 
mobile: redmi  k20 pro 
The problem is still
