### ISSUE TITLE
Tusky crashes once Ntfy is installed

### ISSUE THREAD

**Issue by kdltr** [tuskyapp/Tusky#3881] opened 2023-07-26 14:16 UTC
I’ve installed Ntfy to try out the push notifications, and since it’s installed, Tusky crashes every time I try to open it.

Here’s what I could see from logcat
```
07-26 15:46:53.403 13460 13483 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
07-26 15:46:53.403 13460 13483 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 13460
07-26 15:46:53.403 13460 13483 E AndroidRuntime: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: AccountEntity.pushServerKey (code 1299 SQLITE_CONSTRAINT_NOTNULL)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at x1.g.U(Unknown Source:2)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at p1.i.B(SourceFile:8)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at r7.a.j(SourceFile:16)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at r7.e.c(SourceFile:11)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at b7.v2.s(SourceFile:276)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at qa.a.i(SourceFile:6)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at hb.i0.run(SourceFile:113)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at androidx.appcompat.widget.j.run(SourceFile:15)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at ob.i.run(SourceFile:3)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	at ob.a.run(SourceFile:94)
07-26 15:46:53.403 13460 13483 E AndroidRuntime: 	Suppressed: mb.f: [q1{Cancelling}@4554ed7, Dispatchers.Default]
07-26 15:46:53.409  1772 14715 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-26 15:46:53.410  1772  4993 W ActivityTaskManager:   Force finishing activity com.keylesspalace.tusky/.MainActivity
07-26 15:46:53.425 13460 13483 I Process : Sending signal. PID: 13460 SIG: 9
```

* * * *
- Tusky Version: 23.0
- Android Version: 13
- Android Device: Pixel 4a 5G
- Mastodon instance (if applicable): loutre.info

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2023-07-26 18:50
closing as duplicate of https://github.com/tuskyapp/Tusky/issues/2775
We should definitely not crash

**Closed by connyduck** 2023-07-26 18:50 UTC
