### ISSUE TITLE
Find familiar followers

### ISSUE THREAD

**Issue by olekstomek** [tuskyapp/Tusky#4200] opened 2023-12-28 22:49 UTC
Here is comment with URL to documentation https://github.com/mastodon/mastodon/issues/28329#issuecomment-1854890845 and also in this issue you car read more details (mutual friends and looking for accounts in given profile).

* * * *
- Tusky Version: 4.2.0 (Tusky Test 24.1-7c5238a6)
- Android Version: 14
- Android Device: Samsung A52 5G
- Mastodon instance (if applicable): -

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2023-12-29 06:44
Duplicate of https://github.com/tuskyapp/Tusky/issues/2559

**Closed by connyduck** 2023-12-29 06:44 UTC
