### ISSUE TITLE
Divide the notification section into All, Mentions, and Configurable

### ISSUE THREAD

**Issue by frumble** [tuskyapp/Tusky#2475] opened 2022-04-28 13:01 UTC
The current implementation is clunky if you just want to quickly sort a reply from yesterday out. You have to manually untick the other filters in the drop-down menu and reenable them again after. There should be a 3- or 4-sectioned bar with All, Mentions and one or better two configurables. The configurables could have the current drop-down menu for maximum flexibility. The default view should also be configurable. The bar should disappear the moment you start scrolling.

* * * *
- Tusky Version: 17
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2023-01-28 14:57
Dupe of https://github.com/tuskyapp/Tusky/issues/2378

**Closed** 2023-05-11 14:50 UTC
Labels: enhancement
