### ISSUE TITLE
Crash on opening Notifications area (pixelfed)

### ISSUE THREAD

**Issue by pbielefeldt** [tuskyapp/Tusky#4304] opened 2024-03-03 10:50 UTC
### Detailed description

I use Tusky with two accounts: One on Mastodon (digitalcourage.social) and a second one on Pixelfed (pixey.org).

On Mastodon, I have not had any issues so far.
On Pixelfed, when I open the Notification area (the second tab), Tusky seems to load all notifications, but after ~1 second, the app will crash. It is not clear to me whether that has to do with Pixelfed, the specific Pixelfed instance, or a specific notification (as far as I can see, there are just some "XYZ has likened your post ABC" notifications).

I could try to figure out what happens when deleting the notifications, but that could make it impossible for me to reproduce the error. Maybe I better wait until we find a way to reproduce it somewhere else? I am of the opinion that I was able to open the Notifications tab before without crashing the app – but it might be that I never tried to do so with any unread notifications in it.

### Steps to reproduce the problem

Note that I am not really sure and haven't been able to test!

1. Have to accounts in Tusky, one on Mastodon, one on pixey.org (probably, it is not correlated to these specific services, but I don't know).
2. Get unread notifications on your Pixelfed account (I currently seem to have ~10 XYZ liked your post, an no others)
3. Open the Notifications tab of the Pixelfed account in Tusky → app crashes

I would be willing to create an publish a stacktrace here, but I can't figure out how. I'd appreciate anyone who could tell me…!

### Debug information

Tusky 24.1  Device:  Fairphone FP5 Android version: 13 SDK version: 33  Account:  @derfopps@pixey.org Version: 3.5.3 (compatible; Pixelfed 0.11.12)

**Comment by connyduck** [comment] 2024-03-03 11:19
Yeah sounds like *something* on the second page of notifications is violating the api contract. 
Is there maybe something weird in the notifications when you look at them from the Pixelfed Web interface? Like one for a deleted post, or one by a deleted user, something like that.
Here is an explanation how to get a stacktrace from an Android Device: https://www.browserstack.com/guide/how-to-get-android-app-crash-logs I personally always do it in Android Studio with Usb debugging.

(duplicate of https://github.com/tuskyapp/Tusky/issues/4158)

**Comment by pbielefeldt** [comment] 2024-03-03 11:51
> Yeah sounds like _something_ on the second page of notifications is violating the api contract. Is there maybe something weird in the notifications when you look at them from the Pixelfed Web interface? Like one for a deleted post, or one by a deleted user, something like that. Here is an explanation how to get a stacktrace from an Android Device: https://www.browserstack.com/guide/how-to-get-android-app-crash-logs I personally always do it in Android Studio with Usb debugging.
> 
> (duplicate of #4158)

Thanks! I was able to get me a bugreport.zip. However, I couldn't find a stack trace (`grep -r stacktrace` returns no results, `grep -r exception` returns some findings which to me look irrelevant). Is there a way I can figure out what went wrong? I feel uncomfortable uploading the entire zip, as it apparently contains a huge amount of data, including login information and a lot of things I don't know whether or not they can be uploaded safely.

**Comment by connyduck** [comment] 2024-03-03 11:57
Try searching for com.keylesspalace.tusky

**Comment by pbielefeldt** [comment] 2024-03-03 16:40
Ok, here are some lines from the bugreport.txt that look helpful to me:

```sh
03-03 12:33:05.937  root 13455 13526 I dumpstate: libdebuggerd_client: done dumping process 1139
03-03 12:33:05.937  1058   710   710 W tombstoned: skipping tombstone file creation due to intercept
--------- beginning of crash
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: FATAL EXCEPTION: main
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: Process: com.keylesspalace.tusky, PID: 13317
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at rd.i.D0(SourceFile:15)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at rd.i.Q0(SourceFile:2)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at da.n0.X(SourceFile:5)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at da.n0.Y(SourceFile:3)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at ra.g.<init>(SourceFile:22)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at da.n0.o0(SourceFile:9)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at x9.w.j0(SourceFile:287)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at x9.v.v(SourceFile:1)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at dd.a.j(SourceFile:6)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at td.i0.run(SourceFile:113)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	at ae.a.run(SourceFile:94)
03-03 12:33:05.939 10240 13317 13317 E AndroidRuntime: 	Suppressed: yd.f: [q1{Cancelling}@1beadf7, Dispatchers.Main.immediate]
03-03 12:33:05.940  root 13455 13526 I dumpstate: libdebuggerd_client: started dumping process 1163
03-03 12:33:05.940  1058   710   710 I tombstoned: registered intercept for pid 1163 and type kDebuggerdNativeBacktrace
03-03 12:33:05.942  1041  1163  1163 I libc    : Requested dump for pid 1163 (audioserver)
03-03 12:33:05.944  1000  1515 13592 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-03 12:33:05.944  1000  1515 12412 W ActivityTaskManager:   Force finishing activity com.keylesspalace.tusky/.MainActivity
03-03 12:33:05.955 10105 19965 31351 I NearbyConnections: Processing lost BlePeripheral BlePeripheral{advertisement=BleAdvertisement { version=2, socketVersion=2, serviceIdHash=null, data=[ 0x23 0x53 0x41 0x4a 0x44 0x11 0x32 0xe8 0xc5 0x57 0x35 0xeb 0x7d 0x50 0xee 0xc6 0x32 0xa8 0xcf 0x98 0xf4 0x00 0x03 ], deviceToken=[ 0x76 0xc5 ] }, address=null, psm=0, deviceToken=<ByteString@cf26096 size=2 contents="v\\305">, isSecondProfile=false}.
03-03 12:33:05.956 10105 19965 31351 I NearbyConnections: Lost BleEndpoint for BlePeripheral BlePeripheral{advertisement=BleAdvertisement { version=2, socketVersion=2, serviceIdHash=null, data=[ 0x23 0x53 0x41 0x4a 0x44 0x11 0x32 0xe8 0xc5 0x57 0x35 0xeb 0x7d 0x50 0xee 0xc6 0x32 0xa8 0xcf 0x98 0xf4 0x00 0x03 ], deviceToken=[ 0x76 0xc5 ] }, address=null, psm=0, deviceToken=<ByteString@cf26096 size=2 contents="v\\305">, isSecondProfile=false} (with EndpointId SAJD and EndpointInfo [ 0x32 0xe8 0xc5 0x57 0x35 0xeb 0x7d 0x50 0xee 0xc6 0x32 0xa8 0xcf 0x98 0xf4 0x00 0x03 ]).
03-03 12:33:05.956 10105 19965 32695 I NearbySharing: (REDACTED) Endpoint %s lost over Nearby Connections
03-03 12:33:05.957 10105 19965 31351 I NearbyConnections: ClientProxy(123338705) reporting onEndpointLost(SAJD)
03-03 12:33:05.959 10105 19965  9244 I NearbySharing: (REDACTED) Ignoring lost endpoint %s because we don't have an associated ShareTarget
03-03 12:33:05.964  1000  1515 12412 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
03-03 12:33:05.972 10240 13317 13317 I Process : Sending signal. PID: 13317 SIG: 9
03-03 12:33:05.973  1000  1515  1964 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
03-03 12:33:05.973  1000  1515  1964 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
03-03 12:33:05.978  1000  1515 12412 D CompatibilityInfo: mCompatibilityFlags - 0
03-03 12:33:05.978  1000  1515 12412 D CompatibilityInfo: applicationDensity - 480
03-03 12:33:05.978  1000  1515 12412 D CompatibilityInfo: applicationScale - 1.0
03-03 12:33:05.982  1002  2601  2988 I BtGatt.ScanManager: msg.what = 6
03-03 12:33:05.983  1002  2601  2988 D BtGatt.ScanManager: uid 10105 isForeground true scanMode 1
03-03 12:33:05.983  1002  2601  2988 D BtGatt.ScanManager: uid 10105 isForeground true scanMode 3
03-03 12:33:05.983  1002  2601  2988 D BtGatt.ScanManager: uid 10105 isForeground true scanMode 3
03-03 12:33:05.996  1000  1515 12412 D CompatibilityInfo: mCompatibilityFlags - 0
03-03 12:33:05.996  1000  1515 12412 D CompatibilityInfo: applicationDensity - 480
03-03 12:33:05.996  1000  1515 12412 D CompatibilityInfo: applicationScale - 1.0
03-03 12:33:06.000  1000  1515 12412 D CompatibilityInfo: mCompatibilityFlags - 0
03-03 12:33:06.000  1000  1515 12412 D CompatibilityInfo: applicationDensity - 480
03-03 12:33:06.000  1000  1515 12412 D CompatibilityInfo: applicationScale - 1.0
03-03 12:33:06.001  1000  4566 15132 D iris@ForegroundUtils: onForegroundActivitiesChanged: pid = 4728, uid = 1000, foregroundActivities = true
```

```sh
03-03 12:25:01.266  1000  1515 11093 I wm_task_moved: [467,1,4]
03-03 12:25:01.266  1000  1515 11093 I wm_create_activity: [0,73197444,467,com.keylesspalace.tusky/.MainActivity,NULL,NULL,NULL,0]
03-03 12:25:01.267  1000  1515 11093 I wm_pause_activity: [0,156346866,com.keylesspalace.tusky/.SplashActivity,userLeaving=true,resumeTopActivity]
03-03 12:25:01.269  1000  1515 11093 I wm_finish_activity: [0,156346866,467,com.keylesspalace.tusky/.SplashActivity,app-request]
03-03 12:25:01.269 10240   408   408 I wm_on_create_called: [156346866,com.keylesspalace.tusky.SplashActivity,performCreate]
03-03 12:25:01.276  1000  1515 12206 I wm_add_to_stopping: [0,156346866,com.keylesspalace.tusky/.SplashActivity,completeFinishing]
03-03 12:25:01.277  1000  1515 12206 I wm_restart_activity: [0,73197444,467,com.keylesspalace.tusky/.MainActivity]
03-03 12:25:01.278  1000  1515 12206 I wm_set_resumed_activity: [0,com.keylesspalace.tusky/.MainActivity,minimalResumeActivityLocked - onActivityStateChanged]
03-03 12:25:01.278  1000  1515  1926 I sysui_multi_action: [757,803,799,window_time_0,802,0]
03-03 12:25:01.315 10240   408   408 I wm_on_create_called: [73197444,com.keylesspalace.tusky.MainActivity,performCreate]
03-03 12:25:01.317 10240   408   408 I wm_on_start_called: [73197444,com.keylesspalace.tusky.MainActivity,handleStartActivity]
03-03 12:25:01.319 10240   408   408 I wm_on_resume_called: [73197444,com.keylesspalace.tusky.MainActivity,RESUME_ACTIVITY]
03-03 12:25:01.325 10240   408   408 I wm_on_top_resumed_gained_called: [73197444,com.keylesspalace.tusky.MainActivity,topStateChangedWhenResumed]
03-03 12:25:01.340  1000  1515  1933 I input_focus: [Focus request 3f1a687 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity,reason=UpdateInputWindows]
03-03 12:25:01.405  1000  1515  2377 I input_focus: [Focus entering 3f1a687 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server),reason=Window became focusable. Previous reason: NOT_VISIBLE]
03-03 12:25:01.406  1000  1515  1926 I sysui_multi_action: [319,44,321,41,322,195,325,111939,757,761,758,8,759,1,806,com.keylesspalace.tusky,871,com.keylesspalace.tusky.MainActivity,904,com.keylesspalace.tusky,905,0,1320,8,1321,5]
03-03 12:25:01.406  1000  1515  1926 I wm_activity_launch_time: [0,73197444,com.keylesspalace.tusky/.MainActivity,195]
03-03 12:25:01.772  1000  1515  1932 I wm_destroy_activity: [0,156346866,467,com.keylesspalace.tusky/.SplashActivity,finish-imm:idle]
03-03 12:25:01.773  1000  1515  1932 I wm_stop_activity: [0,267186906,com.android.launcher3/com.android.searchlauncher.SearchLauncher]
03-03 12:25:01.774 10240   408   408 I wm_on_destroy_called: [156346866,com.keylesspalace.tusky.SplashActivity,performDestroy]
03-03 12:25:01.787  1000  1515  1933 I wm_wallpaper_surface: [0,0,null]
03-03 12:25:01.797 10166  2909  2909 I wm_on_stop_called: [267186906,com.android.searchlauncher.SearchLauncher,STOP_ACTIVITY_ITEM]
03-03 12:25:02.414  1000  1515  1931 I commit_sys_config_file: [notification-policy,111929069]
03-03 12:25:02.429  1000  1515  2377 I input_interaction: Interaction with: 3f1a687 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server), PointerEventDispatcher0 (server), 
03-03 12:25:03.178  1000  1515 12206 I am_crash: [408,0,com.keylesspalace.tusky,549994052,java.lang.NullPointerException,Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference,SourceFile,15]
03-03 12:25:03.180  1000  1515 12206 I wm_finish_activity: [0,73197444,467,com.keylesspalace.tusky/.MainActivity,force-crash]
03-03 12:25:03.180  1000  1515 12206 I wm_task_moved: [1,1,4]
03-03 12:25:03.181  1000  1515 12206 I wm_task_moved: [244,1,2147483647]
03-03 12:25:03.181  1000  1515 12206 I wm_task_to_front: [0,244]
03-03 12:25:03.181  1000  1515 12206 I wm_focused_root_task: [0,0,1,467,finish-top adjustFocusToNextFocusableTask]
03-03 12:25:03.181  1000  1515 12206 I wm_set_resumed_activity: [0,com.android.launcher3/com.android.searchlauncher.SearchLauncher,finish-top adjustFocusToNextFocusableTask]
03-03 12:25:03.189  1000  1515 12206 I wm_pause_activity: [0,73197444,com.keylesspalace.tusky/.MainActivity,userLeaving=false,finish]
03-03 12:25:03.192  1000  1515  1933 I input_focus: [Requesting to set focus to null window,reason=UpdateInputWindows]
03-03 12:25:03.194  1000  1515 12206 I sysui_multi_action: [757,316,758,4,759,-1]
03-03 12:25:03.222  1000  1515  2377 I input_focus: [Focus leaving 3f1a687 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server),reason=Waiting for window because NOT_FOCUSABLE]
03-03 12:25:03.237  1000  1515 11928 I am_proc_died: [0,408,com.keylesspalace.tusky,100,2]
03-03 12:25:03.242  1000  1515 11928 I am_schedule_service_restart: [0,com.keylesspalace.tusky/androidx.work.impl.background.systemjob.SystemJobService,1000]
03-03 12:25:03.242  1000  1515 11928 I am_uid_stopped: 10240
03-03 12:25:03.244  1000  1515 11928 I wm_set_resumed_activity: [0,com.android.launcher3/com.android.searchlauncher.SearchLauncher,resumeTopActivity - onActivityStateChanged]
03-03 12:25:03.245  1000  1515 11928 I wm_resume_activity: [0,267186906,244,com.android.launcher3/com.android.searchlauncher.SearchLauncher]
03-03 12:25:03.246 10166  2909  2909 I wm_on_restart_called: [267186906,com.android.searchlauncher.SearchLauncher,performRestartActivity]
03-03 12:25:03.251 10166  2909  2909 I wm_on_start_called: [267186906,com.android.searchlauncher.SearchLauncher,handleStartActivity]
03-03 12:25:03.252 10166  2909  2909 I wm_on_resume_called: [267186906,com.android.searchlauncher.SearchLauncher,RESUME_ACTIVITY]
03-03 12:25:03.300  1000  1515  1933 I input_focus: [Focus request 59fb021 com.android.launcher3/com.android.searchlauncher.SearchLauncher,reason=UpdateInputWindows]
03-03 12:25:03.321  1000  1515  1933 I wm_wallpaper_surface: [0,1,Window{59fb021 u0 com.android.launcher3/com.android.searchlauncher.SearchLauncher}]
03-03 12:25:03.333  1000  1515  1933 I wm_task_removed: [467,removeChild:removeChild last r=ActivityRecord{45ce784 u0 com.keylesspalace.tusky/.MainActivity} t-1 f}} in t=Task{c792ab5 #467 type=standard A=10240:com.keylesspalace.tusky}]
03-03 12:25:03.333  1000  1515  1933 I wm_task_removed: [467,removeChild]
03-03 12:25:03.345  1000  1515  2377 I input_focus: [Focus entering 59fb021 com.android.launcher3/com.android.searchlauncher.SearchLauncher (server),reason=Window became focusable. Previous reason: NOT_VISIBLE]
03-03 12:25:03.685 10166  2909  2909 I wm_on_top_resumed_gained_called: [267186906,com.android.searchlauncher.SearchLauncher,topStateChangedWhenResumed]
03-03 12:25:04.495  1000  1515  2377 I input_interaction: Interaction with: 714b2cd NavigationBar0 (server), PointerEventDispatcher0 (server), 
03-03 12:25:05.112  1000  1515  2345 I commit_sys_config_file: [settings-1-0,5]
03-03 12:25:05.226  1000  1515  3574 I wm_task_moved: [1,1,4]
03-03 12:25:05.233  1000  1515  3574 I wm_task_moved: [467,1,4]
03-03 12:25:05.233  1000  1515  3574 I wm_task_to_front: [0,467]
03-03 12:25:05.234  1000  1515  3574 I wm_focused_root_task: [0,0,467,1,reuseOrNewTask]
03-03 12:25:05.234  1000  1515  3574 I wm_create_activity: [0,111730727,467,com.keylesspalace.tusky/.SplashActivity,android.intent.action.MAIN,NULL,NULL,271581184]
03-03 12:25:05.238  1000  1515  3574 I wm_pause_activity: [0,267186906,com.android.launcher3/com.android.searchlauncher.SearchLauncher,userLeaving=true,pauseBackTasks]
03-03 12:25:05.241 10166  2909  2909 I wm_on_top_resumed_lost_called: [267186906,com.android.searchlauncher.SearchLauncher,topStateChangedWhenResumed]
03-03 12:25:05.242 10166  2909  2909 I wm_on_paused_called: [267186906,com.android.searchlauncher.SearchLauncher,performPause]
03-03 12:25:05.243  1000  1515  1932 I am_uid_running: 10240
03-03 12:25:05.246  1000  1515 11093 I wm_add_to_stopping: [0,267186906,com.android.launcher3/com.android.searchlauncher.SearchLauncher,makeInvisible]
03-03 12:25:05.246  1000  1515  1926 I sysui_multi_action: [757,803,799,window_time_0,802,4]
03-03 12:25:05.251  1000  1515  1965 I am_proc_start: [0,4173,10240,com.keylesspalace.tusky,next-top-activity,{com.keylesspalace.tusky/com.keylesspalace.tusky.SplashActivity}]
03-03 12:25:05.266  1000  1515  3574 I am_proc_bound: [0,4173,com.keylesspalace.tusky]
03-03 12:25:05.268  1000  1515  3574 I wm_restart_activity: [0,111730727,467,com.keylesspalace.tusky/.SplashActivity]
03-03 12:25:05.268  1000  1515  3574 I wm_set_resumed_activity: [0,com.keylesspalace.tusky/.SplashActivity,minimalResumeActivityLocked - onActivityStateChanged]
03-03 12:25:05.269  1000  1515  1932 I am_uid_active: 10240
03-03 12:25:05.274  1000  1515  2377 I input_focus: [Focus leaving 59fb021 com.android.launcher3/com.android.searchlauncher.SearchLauncher (server),reason=NO_WINDOW]
03-03 12:25:05.338  1000  1515  3574 I wm_task_moved: [467,1,4]
03-03 12:25:05.338  1000  1515  3574 I wm_create_activity: [0,152826224,467,com.keylesspalace.tusky/.MainActivity,NULL,NULL,NULL,0]
03-03 12:25:05.339  1000  1515  3574 I wm_pause_activity: [0,111730727,com.keylesspalace.tusky/.SplashActivity,userLeaving=true,resumeTopActivity]
03-03 12:25:05.342  1000  1515 11928 I wm_finish_activity: [0,111730727,467,com.keylesspalace.tusky/.SplashActivity,app-request]
03-03 12:25:05.343 10240  4173  4173 I wm_on_create_called: [111730727,com.keylesspalace.tusky.SplashActivity,performCreate]
03-03 12:25:05.351  1000  1515 11093 I wm_add_to_stopping: [0,111730727,com.keylesspalace.tusky/.SplashActivity,completeFinishing]
03-03 12:25:05.352  1000  1515 11093 I wm_restart_activity: [0,152826224,467,com.keylesspalace.tusky/.MainActivity]
03-03 12:25:05.352  1000  1515 11093 I wm_set_resumed_activity: [0,com.keylesspalace.tusky/.MainActivity,minimalResumeActivityLocked - onActivityStateChanged]
03-03 12:25:05.353  1000  1515  1926 I sysui_multi_action: [757,803,799,window_time_0,802,0]
03-03 12:25:05.394 10240  4173  4173 I wm_on_create_called: [152826224,com.keylesspalace.tusky.MainActivity,performCreate]
03-03 12:25:05.395 10240  4173  4173 I wm_on_start_called: [152826224,com.keylesspalace.tusky.MainActivity,handleStartActivity]
03-03 12:25:05.398 10240  4173  4173 I wm_on_resume_called: [152826224,com.keylesspalace.tusky.MainActivity,RESUME_ACTIVITY]
03-03 12:25:05.404 10240  4173  4173 I wm_on_top_resumed_gained_called: [152826224,com.keylesspalace.tusky.MainActivity,topStateChangedWhenResumed]
03-03 12:25:05.413  1000  1515  1933 I input_focus: [Focus request 4ea26ff com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity,reason=UpdateInputWindows]
03-03 12:25:05.481  1000  1515  1926 I sysui_multi_action: [319,45,321,35,322,251,325,111943,757,761,758,7,759,1,806,com.keylesspalace.tusky,871,com.keylesspalace.tusky.MainActivity,904,com.keylesspalace.tusky,905,0,945,39,1320,8,1321,5]
03-03 12:25:05.482  1000  1515  1926 I wm_activity_launch_time: [0,152826224,com.keylesspalace.tusky/.MainActivity,251]
03-03 12:25:05.493  1000  1515  2377 I input_focus: [Focus entering 4ea26ff com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server),reason=Window became focusable. Previous reason: NOT_VISIBLE]
03-03 12:25:05.608  1000  1515  1933 I wm_wallpaper_surface: [0,0,null]
03-03 12:25:05.611  1000  1515  1932 I wm_destroy_activity: [0,111730727,467,com.keylesspalace.tusky/.SplashActivity,finish-imm:idle]
03-03 12:25:05.611  1000  1515  1932 I wm_stop_activity: [0,267186906,com.android.launcher3/com.android.searchlauncher.SearchLauncher]
03-03 12:25:05.613 10240  4173  4173 I wm_on_destroy_called: [111730727,com.keylesspalace.tusky.SplashActivity,performDestroy]
03-03 12:25:05.629 10166  2909  2909 I wm_on_stop_called: [267186906,com.android.searchlauncher.SearchLauncher,STOP_ACTIVITY_ITEM]
03-03 12:25:05.937  1000  1515  1931 I commit_sys_config_file: [notification-policy,111932592]
03-03 12:25:06.294  1000  1515 11093 I wm_task_moved: [1,0,0]
03-03 12:25:06.294  1000  1515 11093 I wm_task_moved: [1,0,3]
03-03 12:25:06.296  1000  1515 11093 I wm_wallpaper_surface: [0,1,Window{4ea26ff u0 com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity}]
03-03 12:25:06.307 10166  2909  2909 I wm_on_restart_called: [267186906,com.android.searchlauncher.SearchLauncher,performRestartActivity]
03-03 12:25:06.307  1000  1515  1933 I input_focus: [Focus request recents_animation_input_consumer,reason=UpdateInputWindows]
03-03 12:25:06.309 10166  2909  2909 I wm_on_start_called: [267186906,com.android.searchlauncher.SearchLauncher,handleStartActivity]
03-03 12:25:06.329 10166  2909  2909 I sysui_latency: [1,-303237011]
03-03 12:25:06.338  1000  1515  1926 I sysui_multi_action: [319,4,322,41,325,111944,757,761,758,9,759,5,806,com.android.launcher3,871,com.android.searchlauncher.SearchLauncher,904,com.google.android.apps.wellbeing,905,0,1320,9,1321,22]
03-03 12:25:06.342  1000  1515  2377 I input_focus: [Focus leaving 4ea26ff com.keylesspalace.tusky/com.keylesspalace.tusky.MainActivity (server),reason=setFocusedWindow]
03-03 12:25:06.343  1000  1515  2377 I input_focus: [Focus entering recents_animation_input_consumer (server),reason=setFocusedWindow]
03-03 12:25:06.636  1000  1515  1926 I sysui_latency: [8,40]
03-03 12:25:06.679  1000  1515  2377 I input_interaction: Interaction with: recents_animation_input_consumer (server), PointerEventDispatcher0 (server), 
03-03 12:25:07.813  1000  1515 11928 I wm_task_moved: [1,1,4]
03-03 12:25:07.820  1000  1515 11928 I wm_focused_root_task: [0,0,1,467,startActivityFromRecents]
03-03 12:25:07.821 10240  4173  4173 I wm_on_top_resumed_lost_called: [152826224,com.keylesspalace.tusky.MainActivity,topStateChangedWhenResumed]
03-03 12:25:07.822  1000  1515 11928 I wm_task_moved: [466,1,4]
03-03 12:25:07.822  1000  1515 11928 I wm_task_to_front: [0,466]
03-03 12:25:07.822  1000  1515 11928 I wm_focused_root_task: [0,0,466,1,moveTaskToFront findTaskToMoveToFront]
03-03 12:25:07.823  1000  1515 11928 I wm_set_resumed_activity: [0,com.android.settings/.SubSettings,moveTaskToFront findTaskToMoveToFront]
03-03 12:25:07.825  1000  1515 11928 I wm_pause_activity: [0,152826224,com.keylesspalace.tusky/.MainActivity,userLeaving=true,pauseBackTasks]
03-03 12:25:07.850 10240  4173  4173 I wm_on_paused_called: [152826224,com.keylesspalace.tusky.MainActivity,performPause]
03-03 12:25:07.856  1000  1515 11928 I wm_set_resumed_activity: [0,com.android.settings/.SubSettings,resumeTopActivity - onActivityStateChanged]
03-03 12:25:07.857  1000  1515 11928 I wm_add_to_stopping: [0,152826224,com.keylesspalace.tusky/.MainActivity,makeInvisible]
03-03 12:25:07.858  1000  1515 11928 I wm_resume_activity: [0,68809820,466,com.android.settings/.SubSettings]
03-03 12:25:07.859  1000  1515  1926 I sysui_multi_action: [757,803,799,window_time_0,802,2]
03-03 12:25:07.862  1000 31534 31534 I wm_on_restart_called: [68809820,com.android.settings.SubSettings,performRestartActivity]
03-03 12:25:07.864  1000 31534 31534 I wm_on_start_called: [68809820,com.android.settings.SubSettings,handleStartActivity]
03-03 12:25:07.868  1000 31534 31534 I snet_event_log: [120484087,-1,]
03-03 12:25:07.870  1000 31534 31534 I wm_on_resume_called: [68809820,com.android.settings.SubSettings,RESUME_ACTIVITY]
03-03 12:25:07.874  1000 31534 31534 I sysui_multi_action: [757,39,758,1,833,34,1089,0]
03-03 12:25:07.884 radio  2804  3383 I service_manager_stats: [100,65,356897]
03-03 12:25:07.937  1000 31534 31534 I auditd  : type=1400 audit(0.0:44561): avc: denied { read } for comm="pool-2-thread-7" name="pagetypeinfo" dev="proc" ino=4026531857 scontext=u:r:system_app:s0 tcontext=u:object_r:proc_pagetypeinfo:s0 tclass=file permissive=0
03-03 12:25:07.941  1000 31534 31534 I auditd  : type=1400 audit(0.0:44562): avc: denied { search } for comm="pool-2-thread-7" name="zram0" dev="sysfs" ino=59906 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_zram:s0 tclass=dir permissive=0
03-03 12:25:07.945  1000 31534 31534 I auditd  : type=1400 audit(0.0:44563): avc: denied { search } for comm="pool-2-thread-7" name="zram0" dev="sysfs" ino=59906 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs_zram:s0 tclass=dir permissive=0
03-03 12:25:07.972  1000 31534 31534 I wm_on_top_resumed_gained_called: [68809820,com.android.settings.SubSettings,topWhenResuming]
03-03 12:25:08.020  1000  1515  1926 I sysui_multi_action: [319,49,321,30,322,192,325,111945,757,761,758,9,759,4,806,com.android.settings,871,com.android.settings.SubSettings,904,com.android.settings,905,0,1320,8,1321,5]
03-03 12:25:08.245  1000  1515 11093 I wm_task_moved: [1,0,2]
03-03 12:25:08.245  1000  1515 11093 I wm_add_to_stopping: [0,267186906,com.android.launcher3/com.android.searchlauncher.SearchLauncher,makeInvisible]
```

Maybe some of this helps?
I kindof assume the `java.lang.NullPointerException` is relevant… I just don't see where it comes from (these are not the file names given, are they?)

**Comment by connyduck** [comment] 2024-03-04 06:33
Thx, that helps very much!

Here is the deobfuscated stacktrace:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
 	at kotlin.text.StringsKt__StringsKt.indexOf(Strings.kt:1103)
 	at kotlin.text.StringsKt__StringsJVMKt.replace(StringsJVM.kt:88)
 	at kotlin.text.StringsKt__StringsJVMKt.replace$default(StringsJVM.kt:86)
 	at com.keylesspalace.tusky.util.StatusParsingHelper.parseAsMastodonHtml(StatusParsingHelper.java:34)
 	at com.keylesspalace.tusky.util.StatusParsingHelper.parseAsMastodonHtml$default(StatusParsingHelper.java:33)
 	at com.keylesspalace.tusky.viewdata.StatusViewData$Concrete.<init>(StatusViewData.kt:49)
 	at com.keylesspalace.tusky.util.ViewDataUtils.toViewData(ViewDataUtils.kt:51)
 	at com.keylesspalace.tusky.util.ViewDataUtils.toViewData$default(ViewDataUtils.kt:45)
 	at com.keylesspalace.tusky.components.timeline.viewmodel.NetworkTimelineRemoteMediator.load(NetworkTimelineRemoteMediator.kt:83)
 	at com.keylesspalace.tusky.components.timeline.viewmodel.NetworkTimelineRemoteMediator$load$1.invokeSuspend(NetworkTimelineRemoteMediator.kt)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

So from this we can get there is a notification with a status that has a no content. I think we can fix that on Tusky side but @dansup should check Pixelfed code as well.

**Comment by connyduck** [comment] 2024-03-04 19:45
Will be fixed on Pixelfed side

**Closed by connyduck** 2024-03-04 19:45 UTC
Labels: bug
