### ISSUE TITLE
Home timeline ends

### ISSUE THREAD

**Issue by AaronM04** [tuskyapp/Tusky#997] opened 2019-01-18 18:07 UTC
I can scroll to the bottom of my home timeline and there are no more toots even though I know there should be.

There is no option to refresh either.

* * * *
- Tusky Version: 4.1
- Android Version: LineageOS 14.1, Android 7.1.2
- Android Device: oneplus 3t
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-01-18 18:24
Hey
Thanks for reporting
Just to make sure: it's not ended on the server and you can scroll to this place in the web app after page reload but not in the app?

**Comment by AaronM04** [comment] 2019-01-18 18:30
I have not tried that. Next time I can reproduce the problem, I'll try this and report back.

**Comment by charlag** [comment] 2019-01-18 18:31
Thanks. Server keeps only latest 400 statuses I think so this may be the case.

**Comment by AaronM04** [comment] 2019-01-18 18:31
@charlag if it is the server's fault, I think there should be a way for the user to try and refresh it within Tusky. Does that seem reasonable?

**Comment by charlag** [comment] 2019-01-18 18:32
It'a not a fault, it's by design. I don't see why you need refresh.

**Comment by AaronM04** [comment] 2019-01-18 18:54
Is there another way to keep scrolling arbitrarily far through the home timeline? That's what I want to do.

**Comment by charlag** [comment] 2019-01-18 18:56
With timeline cache (in the nightly now) we try to save it to the database and retrieve id you're offline/timeline ends (I don't remmeber if we disabled some of this for techincal reasons now though). But that's only what you've seen

**Comment by AaronM04** [comment] 2019-01-19 06:49
I reproduced the problem, and the webapp has 1 toot more than Tusky. So you seem to be mostly right.

**Comment by charlag** [comment] 2019-01-19 07:45
It could be that while you've been scrolling it was already pushed out.
Thanks for trying it out and verifying, though, let us know id you find more.

**Comment by charlag** [comment] 2019-01-19 16:09
I'm closing this for now, feel free to reopen if you think that we really miss something in the timeline.

**Closed by charlag** 2019-01-19 16:09 UTC
