### ISSUE TITLE
sort accounts (product request)

### ISSUE THREAD

**Issue by RJGhugo** [tuskyapp/Tusky#3686] opened 2023-05-23 11:51 UTC
Tuskey allows to manage several accounts.

It would be useful to sort the account manually (e.g. most used first) and not only sorted as they are created.

**Comment by nikclayton** [comment] 2023-05-25 10:16
Dupe of https://github.com/tuskyapp/Tusky/issues/1259

**Closed** 2023-05-31 09:14 UTC
