### ISSUE TITLE
Deleting the last filter shows "nothing here" and last filter

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#3839] opened 2023-07-11 19:54 UTC
![Screenshot_20230711-183017](https://github.com/tuskyapp/Tusky/assets/10157047/57e85fc6-9ad4-43e5-93c9-14282bb0432f)

Steps to reproduce:
- Go to Account Preferences -> Filters.
- (create filters if there are none)
- delete all filters
- deleting the last filter shows "nothing here" but the last filter is still visible (see screenshot)
- clicking delete again leads to error message
- opening and closing the screen correctly shows just "nothing here"

Expectde behavior:
The last filter goes away when it is deleted and just "Nothing here" is shown.

* * * *
- Tusky Version: 23.0
- Android Version: 12
- Android Device: Fairphone 4
- Mastodon instance: chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2023-07-12 13:43
Dupe of https://github.com/tuskyapp/Tusky/issues/3525 ?

**Closed** 2023-07-27 11:44 UTC
Labels: bug
