### ISSUE TITLE
Media loading screen doesn’t appear when reopened

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#950] opened 2018-12-05 17:41 UTC
When trying to open a media, you get a loading screen. If you go back and try to open it again before the media has fully charged, the loading screen doesn’t appear. It seems the UI is blocked, waiting for the media to load, because you can’t interact with anything unless you hit back, and as soon as the media is loaded it appears like you just clicked on it.

How to reproduce:

1. Click on a media: loading screen appears
2. Press back
3. Click on the media again: loading screen should appear but doesn’t
4. You can’t interact with anything until media is loaded

<details><summary>Video demonstration</summary>
<p>

Notice the loading screen, then I hit back, then I hit the image again (when the eye icon disappear).

![screenrecord-2018-12-05-18-12-42](https://user-images.githubusercontent.com/2446451/49532142-27331780-f8bc-11e8-9932-410fae7359d7.gif)
</p>
</details>

* * * *
- Tusky Version: 4.0
- Android Version: 8.1.0
- Android Device: Oneplus 5

**Comment by ariasuni** [comment] 2018-12-05 18:50
That’s the current behavior but the loading view doesn’t appear if we go back and try to reopen it.

I updated the instructions to reproduce the bug, hope it’s clearer now.

**Comment by charlag** [comment] 2019-01-19 19:21
While #968 comes later, I think it has a better description.
Duplicate of #968

**Closed by charlag** 2019-01-19 19:21 UTC
