### ISSUE TITLE
always load new posts in the same direction

### ISSUE THREAD

**Issue by spicewiesel** [tuskyapp/Tusky#2496] opened 2022-05-03 14:22 UTC
After refreshing the "Home" tab new posts are shown _above_ the current position.
Posts loaded using the "load more" button are then shown _below_ the current position.

That frequentially leads to a situation where I have new posts to read above and below my current position and that's quite confusing.

Expectation: Always put new posts in the same direction. If the reading direction (new posts on top or bottom) is configurable the loading direction could be dependend on that.

* * * *
- Tusky Version: 17.0
- Android Version: 12
- Android Device: Pixel 5
- Mastodon instance (if applicable): toot.berlin

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by 68kmentat** [comment] 2022-05-07 12:06
I believe that the "load more" button is supposed to load in either direction, depending on whether it is in the top half or the bottom half of the screen. That may still be confusing for users but I personally appreciated that function. 

It actually hasn't been doing that for me since a recent update, I came here to find out if the change was intentional or a bug

**Comment by spicewiesel** [comment] 2022-05-09 07:05
Personal preferences aside I don't see the benefit from positioning new posts in two different directions, having new posts below and above your current position. It just breaks the flow of reading.

**Comment by charlag** [comment] 2022-05-10 18:39
I believe this is a duplicate of #2423

**Closed by charlag** 2022-05-10 18:39 UTC
