### ISSUE TITLE
Timestamp obscured by username in timeline

### ISSUE THREAD

**Issue by archaeme** [tuskyapp/Tusky#920] opened 2018-11-15 02:55 UTC
Minor cosmetic bug. Some long usernames end up obscuring the timestamp of a post on the timeline.
![screenshot_20181114-215401__01](https://user-images.githubusercontent.com/802788/48527082-e7968400-e857-11e8-8b35-c51ff27652b3.jpg)

* * * *
- Tusky Version: 3.1
- Android Version: 9
- Android Device: OnePlus 6
- Mastodon instance (if applicable): niu.moe

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2018-11-15 21:06
duplicate of https://github.com/tuskyapp/Tusky/issues/481

**Closed by connyduck** 2018-11-15 21:06 UTC
Labels: duplicate

**Comment by archaeme** [comment] 2018-11-16 01:33
Huh, somehow didn't catch that on my initial search. Thanks.
