### ISSUE TITLE
Load More button doesn't maintain your place in the TL anymore & doesn't load forward correctly 

### ISSUE THREAD

**Issue by 68kmentat** [tuskyapp/Tusky#2508] opened 2022-05-07 12:16 UTC
The "Load More" button used to load more posts backwards ifromn time from your current position if the button was at the bottom of the screen, or forwards in time if it was an the top of your screen.

It has now reverted to the glitchy behavior that it used to have long ago, where the only way to load posts forward in time from the current position is to press the button and immediately scroll down to older posts, so that the button is off screen by the time it actually loads anything.

The worst problem with the current functionality is that the newly loaded posts also scroll you away from whatever posts you were reading at the time, losing your place

I hope that this makes sense, I can provide a video or some more explanation on request

* * * *
- Tusky Version: 17.0
- Android Version: 10 (QZKS30.Q4-40-95-9)
- Android Device: Motorola One 5G Ace

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by foss-** [comment] 2022-05-09 10:45
Dupe of https://github.com/tuskyapp/Tusky/issues/89

**Comment by charlag** [comment] 2022-05-10 18:36
HI, it's a duplicate of #2423

**Closed by charlag** 2022-05-10 18:36 UTC
