### ISSUE TITLE
feature request: include URL of (or reference to) toot/post in filename of saved media

### ISSUE THREAD

**Issue by eternalbit** [tuskyapp/Tusky#1015] opened 2019-01-29 14:46 UTC
**Feature Request:** include the URL of a toot/post in filename when saving media (image/video/audio/...)

**Rationale:** when saving media as local file the link to the origin gets lost. It's just a file with some kind of ID as filename. No easy/convenient way to find out which toot/post it came from.

It would be awesome, if the filename contained a full reference to the origin.

**Possible Implementation:** the filename could simply be the URL of the toot but since the character '/' isn't allowed in filenames it could be replaced by '|' or ' ' ... it should work on android & linux at least.

**Example:**
This image in this toot **https://mastodon.art/@MJBlacke/100622741819071211** ... could be saved with the filename
**mastodon.art|@MJBlacke|100622741819071211.jpg**
 or
**mastodon.art @MJBlacke 100622741819071211.jpg**

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-01-30 19:14
Hey
I see the use case but I think it's a privacy risk. Most people don't check filenames, especially on mobile. For one case where it is needed there will be 5 where people will forget to remove it.
I slightly oppose it, but I'm opening to hearing opinions of others.

**Comment by charlag** [comment] 2019-02-02 16:40
We try to keep options at minimum and only include critical things so it is easy to use.

EXIF is stripped by Mastodon as far as I know.

**Comment by charlag** [comment] 2019-05-26 14:37
Duplicate of #508 ?

**Closed by charlag** 2019-05-26 14:37 UTC
