### ISSUE TITLE
reload view of status after editing it

### ISSUE THREAD

**Issue by mooseyboots** [tuskyapp/Tusky#3465] opened 2023-03-18 15:31 UTC
[Issue text goes here].

* * * *
- Tusky Version: 21
- Android Version: 13, calyxos 4.7
- Android Device: pixel 4a
- Mastodon instance (if applicable):

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

if i'm in thread view, and i edit a status of mine there, the thread doesn't reload so my old status is still displayed.

**Comment by Lakoja** [comment] 2023-03-19 08:25
Slightly related and/or duplicate?
https://github.com/tuskyapp/Tusky/issues/3366

**Comment by Tak** [comment] 2023-03-20 07:27
Duplicate of #3366

**Closed** 2023-03-20 07:35 UTC

**Comment by mooseyboots** [comment] 2023-03-20 09:51
this is not a duplicate. there's no duplication of the display of statuses. only the old version of the status is displayed after an edit, the new one does not appear, for, as i already said, the thread is not reloaded. the other issue involves the display of both old and new, which means the page is reloaded, but wrongly, correct?
