### ISSUE TITLE
Losing post draft to automatic refresh

### ISSUE THREAD

**Issue by Skiri-ki** [tuskyapp/Tusky#4258] opened 2024-02-17 16:33 UTC
Lately when composing longer posts, tabbing in and out and going above the 500 char limit and back below, there are occasional refresh/reload events in the app that will close the composer without saving the draft, losing the entire thing.

This seems to mostly be timing based.

**Comment by connyduck** [comment] 2024-02-17 17:50
What is your device and which other app are you tabbing to?

**Comment by Skiri-ki** [comment] 2024-02-17 20:49
OnePlus 12 5G, Oxygen OS 14.0, tabbing to the OnePlus Gallery and Notes apps. Though the draft doesn't disappear on tabbing back but just after some longer period in the app, sometimes while typing.

**Comment by connyduck** [comment] 2024-02-19 08:17
Ok so its not a case of the backgrounded app being killed because it takes too much memory 🤔 
Maybe its a crash but the crash dialog is not shown?
There are no refresh/reload events that could impact the compose screen.

**Comment by guerda** [comment] 2024-09-16 20:04
I have the same issue with my Pixel 7. Even with smaller texts. It's worse if you have an image attached and want to write an alt text. I don't know if Tusky gets killed in the meantime.
It would be great if the toots could automatically be stored as draft.

**Comment by connyduck** [comment] 2024-09-28 05:53
Is this still happening? It should be fixed by https://github.com/tuskyapp/Tusky/pull/4685

**Comment by guerda** [comment] 2024-10-03 07:46
I still have 26.2 although I'm part of the beta tester group. With 26.2 it still happens. I compose a draft, switch to some other apps and go back and my main timeline is shown again.

Would it be a possibility to automatically store those as a draft?

**Comment by guerda** [comment] 2024-10-03 07:51
In the nightly build, I cannot reproduce the bug anymore.

Version 26.2-02d85420
com.keylesspalace.tusky.test

**Closed** 2024-10-11 07:25 UTC

**Comment by guerda** [comment] 2024-11-01 08:35
Hm, unfortunately the bug reappeared in the current version. I just had a draft being completely lost 
Version 26.2
com.keylesspalace.tusky
