### ISSUE TITLE
Side swipe is too sensitive

### ISSUE THREAD

**Issue by SaphireLattice** [tuskyapp/Tusky#2725] opened 2022-10-21 01:35 UTC
When casually scrolling, even smallest sideways gesture results in you switching between timelines. It's literally isage breaking for me and makes it extremely frustrating to use Tusky in any capability...

It would be nice if the side swipe required some actual (if minimal) distance to be triggered, and needed a much tighter angle too. Currently if you brush your finger over time timeline diagonally, it's 50/50 between actual scroll and switching tabs.

* * * *
- Tusky Version: 19.0
- Android Version: 12.1
- Android Device: Samsung A52

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2022-10-21 15:57
There is an option to turn off the swipe completely

Duplicate of https://github.com/tuskyapp/Tusky/issues/2112

**Closed by connyduck** 2022-10-21 15:57 UTC
