### ISSUE TITLE
Old toots stuck on top of home timeline

### ISSUE THREAD

**Issue by LittleFox94** [tuskyapp/Tusky#2663] opened 2022-08-11 08:41 UTC
Hi,

After going on my profile and scrolling to an old toot (knew I tooted it 2022-07-25, so just scrolled there), my home timeline now has toots from roughly that period stuck on top - fresh toots starting ~8 screen sizes below them.

The stuck ones seem to be non-contiguous, I think I should have had more toots in home as it shows. The fresh ones are refreshed, but stay at their place below the stuck ones.

I tried purging the app cache and switching tabs and accounts, without success.

This is pretty obscure, not sure what other info could be useful here or how to reproduce it.. some slightly rusted android dev skills are available, so feel free to ask for any adb thing (or something else) that might help diagnose the problem :)

* * * *
- Tusky Version: 19.0
- Android Version: 12 (SQ3A.220705.003)
- Android Device: Pixel 6 Pro
- Mastodon instance (if applicable): mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate (browsed issues for some pages).

**Comment by connyduck** [comment] 2022-08-11 09:47
Those old toots stuck on top, could they be from a different account that is logged into Tusky or are they definitely from the right one, just in the wrong order?

(logging out and in again or clearing the app data completely will solve the problem temporarily)

**Comment by LittleFox94** [comment] 2022-08-11 10:58
Now that you ask, they actually are from the Home timeline of another account.

And I noticed something even more strange: going to their authors profile via their avatar on the toot brings me to a completely different profile - for every toot by the same author, I go to the same other profile, but multiple authors could go to the same profile (clicking "toby" on stuck toot always brings up "mmcc", clicking any of two different bots gives me Eugen, clicking me gives another account than the one for "toby")

**Comment by LittleFox94** [comment] 2022-08-11 10:59
Those stuck toots could belong to a logged-in account on an instance that is currently offline - maybe some weird form of "old cache + cannot refresh -> not cleared from view"?

**Comment by connyduck** [comment] 2022-08-11 15:44
Ok so this seems to be another incarnation of the "ghost timeline" bug that was supposed to be fixed by https://github.com/tuskyapp/Tusky/commit/f419e83c16438456559163463785ec68ef98fdd3

Basically what happens is that the timeline of one account gets written to the database with the id of another.

It could be reproduced by logging out of one account while a refresh was still ongoing, but since that is fixed there must be another way that it can happen as well 🤔

**Closed** 2024-08-14 16:58 UTC
