### ISSUE TITLE
"load more" experience

### ISSUE THREAD

**Issue by kulimuliF** [tuskyapp/Tusky#2938] opened 2022-11-25 20:57 UTC
If you come back after a while and you have missed a lot of posts, you see the "load more" button, which is loading a bulk of new posts. By clicking on it it, you are at the top or maybe only somewhere at the middle 
of the posts if there is another bulk of messages, which you can load by clicking again on the button.

If you want to continue reading where you have stopped yesterday (old to new), it's awful to find the post where you have paused previously.

Is it possible to leave the focus on the old post, or load the new posts dynamically when you scroll up?

* * * *
- Tusky Version: 19.0, 20beta.1
- Android Version: 12
- Android Device: one plus nird
- Mastodon instance (if applicable): aut.social

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2022-11-26 11:06
Duplicate of https://github.com/tuskyapp/Tusky/issues/2788

**Closed** 2022-11-27 17:29 UTC

**Comment by charlag** [comment] 2022-11-28 11:09
@nikclayton it sorts this way because status IDs are not guaranteed to be numbers, but are sortable. We paginate by ID therefore we must sort by ID.

**Comment by connyduck** [comment] 2022-11-28 11:11
And they are sorted by length first because when they are numbers "2" must come before "12" (which in alphabetic ordering isn't the case)

**Comment by nikclayton** [comment] 2022-11-28 15:33
So the Mastodon server guarantees that sorting by status ID gives you a stable ordering of the statuses? Presumably in the order that they were received by the server? Is that a guarantee in the API docs somewhere and I can't find it, or is this an implementation detail that's effectively baked in to the protocol now?

**Comment by charlag** [comment] 2022-11-28 21:41
They added this info after there was an Incident where we assumed IDs to be a number and in few server impls they aren't. Mastodon predates AP and does not use AP internally nor in the client API (which also predates AP). It has nothing to do with AP objects/activities. I don't know how Mastodon assigns those IDs

**Comment by nikclayton** [comment] 2022-11-29 15:36
Doing some more experimentation, the `min_id` parameter is the one to use (https://docs.joinmastodon.org/methods/timelines/#home).

Consider statuses with IDs 10, 11, 12, ... 20 (in order oldest to newest).

Requesting /api/v1/timeslines/home?limit=5&since_id=5&max_id=20 will return statuses with IDs 15, 16, 17, 18, 19 (i.e., the most recent 5 statuses that are older than max_id).

Requesting /api/v1/timeslines/home?limit=5&min_id=5&max_id=20 will return statuses with IDs 6, 7, 8, 9, 10 (i.e., the 5 statuses immediately after min_id).

I tested this by getting a list of 20 statuses from my home server (`$BEARER` is my bearer token):

```shell
> curl -s -H "Authorization: Bearer $BEARER" https://mastodon.social/api/v1/timelines/home | jq '.[] | .id'
"109427704324062861"
"109427704027664947"
"109427700335673944"
"109427651700797458"
"109427643873506071"
"109427637540665364"
"109427630965842606"
"109427618306902651"
"109427601961094542"
"109427597758498044"
"109427584836740624"
"109427582011671433"
"109427572856131091"
"109427562480195783"
"109427484969388258"
"109427480996210561"
"109427479377818719"
"109427478396118764"
"109427476884220214"
"109427476574683674"
```

and then

## min_id only

Fetching from ...18719 (fourth from bottom)

```shell
> curl -s -H "Authorization: Bearer $BEARER" 'https://mastodon.social/api/v1/timelines/home?limit=5&min_id=109427479377818719' | jq '.[] | .id'
"109427582011671433"
"109427572856131091"
"109427562480195783"
"109427484969388258"
"109427480996210561"
```

Looks correct -- the 5 next statuses from ...18719 onwards

## since_id only

```shell
> curl -s -H "Authorization: Bearer $BEARER" 'https://mastodon.social/api/v1/timelines/home?limit=5&since_id=109427479377818719' | jq '.[] | .id'
"109427756982106944"
"109427754764432860"
"109427704324062861"
"109427704027664947"
"109427700335673944"
```

Returns the most recent 5, not what we want

## min_id and max_id

Set max_id to be ...1091, which is inside the limit of 5

```shell
> curl -s -H "Authorization: Bearer $BEARER" 'https://mastodon.social/api/v1/timelines/home?limit=5&min_id=109427479377818719&max_id=109427572856131091' | jq '.[] | .id'
"109427562480195783"
"109427484969388258"
"109427480996210561"
```

Correctly limits to strictly between min_id and max_id

**Comment by nikclayton** [comment] 2022-11-30 11:41
Ah, might be considerably simpler than that...

**Comment by nikclayton** [comment] 2022-11-30 15:28
... or not.

TimelineFragment has the following code in `onViewCreated`:

```
        adapter.registerAdapterDataObserver(object : RecyclerView.AdapterDataObserver() {
            override fun onItemRangeInserted(positionStart: Int, itemCount: Int) {
                if (positionStart == 0 && adapter.itemCount != itemCount) {
                    binding.recyclerView.post {
                        if (getView() != null) {
                            if (isSwipeToRefreshEnabled) {
                                binding.recyclerView.scrollBy(0, Utils.dpToPx(requireContext(), -30))
                            } else binding.recyclerView.scrollToPosition(0)
                        }
                    }
                }
            }
        })
```

In *theory* you could put the following code after the `if` block:

```
(binding.recyclerView.layoutManager as LinearLayoutManager).scrollToPositionWithOffset(positionStart + itemCount, 0)
```

and it should scroll to the end of the newly added items.

But if I add logging to that function and to `onLoadMore` in the same file to log the parameters I see the following (with `TimelineViewModel.LOAD_AT_ONCE = 4`, so I can see multiple placeholders in a timeline with gaps).

Assume that the "Load More" placeholder is at position 5 in the adapter (i.e., 6th entry in the list), it logs:

```
onLoadMore(5)
onItemRangeInserted(240, 1)
```

The `onLoadMore` log is correct (it's the position of the click, 5). But the new items should be inserted at position 5, not position 241.

Another time I'll see this after clicking:

```
onLoadMore(5)
onItemRangeInserted(3, 4)
onItemRangeInserted(241, 4)
```

which is also strange -- why two calls to onItemRangeInserted(), with very different positions? More investigation needed.

**Comment by nikclayton** [comment] 2022-11-30 16:07
Remembering the position of the "Load More" placeholder, and only scrolling in `onItemRangeInserted` if `positionStart` matches *appears* to work (in *extremely* limited testing).

Commit that does that is https://github.com/tuskyapp/Tusky/commit/34c56220ab504022ed77badaaf8b06b0f36a9af2, complete diff so far is https://github.com/tuskyapp/Tusky/compare/develop...nikclayton:Tusky:load-more-jump.

Per the above, I'm not sure why that's needed.

I'm also wondering if any other "Load more" actions should be blocked in the UI while one is happening. The user hitting one, clicking it, then rapidly scrolling and clicking another one might cause problems (although why they'd do that in the first place...?)

**Comment by Gryzor** [comment] 2022-12-01 08:06
>  why they'd do that in the first place...?
Users are _feral_, they will do all sorts of things either by mistake or due to external reasons (e.g. the device is slow and a gesture is misinterpreted trying to figure out why it's not responding, Android in its infinite wisdom delivers this message to Tusky and the scroll happens...) 

(don't ask me how I know) ;)))

**Comment by nikclayton** [comment] 2022-12-03 19:58
https://github.com/tuskyapp/Tusky/commit/a1c17b48b2a0af059841260dfe2bf4480b64f5a7 stops multiple "Load more" coroutines by disabling the button

**Comment by nikclayton** [comment] 2022-12-03 20:05
The weirdness in `onItemRangeInserted` still nags me -- I still don't understand why the `positionStart` values can sometimes seem to have no relation to the position of the placeholder that was clicked.

A more robust approach might be to note the position and ID of the status immediately below the status when it was clicked (the code already has to do this anyway), and then search for this ID in the adapter after the load has completed. The position of the item with that ID is the position to scroll to.

But that's more complicated, and I'm not sure if it's actually needed.
