### ISSUE TITLE
Beta - Menu disappears with header bar positioned at bottom of the screen

### ISSUE THREAD

**Issue by chiefoldmist** [tuskyapp/Tusky#2954] opened 2022-11-30 13:34 UTC
In settings I moved the navigation bar to be at the bottom of the screen. 

I can now no longer access any menus, so am stuck with this configuration. 

Cannot get to settings, lists, bookmarks, profile, switch accounts. 

* * * *
- Tusky Version: Beta tester - latest version 25th Novmber
- Android Version: 13
- Android Device: Pixel 6
- Mastodon instance (if applicable): mastodon.cloud

- [ ×] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2022-12-01 10:07
Can you swipe right from the left edge of the screen to expose the menu?

**Comment by chiefoldmist** [comment] 2022-12-01 10:53
No, was completely stuck.

Have had to reinstall the app to return to default setup.

Do you want me to see if I can repeat?

**Comment by charlag** [comment] 2022-12-01 10:59
Duplicate of #2473

**Closed by charlag** 2022-12-01 10:59 UTC
