### ISSUE TITLE
Tusky doesn't let me upload audio files

### ISSUE THREAD

**Issue by bonsaiheldin** [tuskyapp/Tusky#1565] opened 2019-11-20 11:27 UTC
Hello. Tusky prohibits to let me upload audio files, even though recent Mastodon versions brought that feature. I guess it just wasn't implemented yet? The web interface allows uploading of MP3 files, i haven't tested other file formats. I think "somewhere on Github" the Mastodon devs wrote down the supported formats, i can't find it now. OGG, OPUS and FLAC were in, too.

https://blog.joinmastodon.org/2019/10/mastodon-3.0/

* * * *
- Tusky Version: 8.1
- Android Version: 6.01
- Android Device: Xiaomi Redmi 3S
- Mastodon instance (if applicable): cybre.space

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JuanjoSalvador** [comment] 2019-11-20 16:10
Tested on Tusky 9.1 too, same issue. I think this is not a Mastodon related issue, more like a future feature that isn't implemented yet because it is not so important.

Anyway, it seems like there is no filter while selecting files.

**Comment by connyduck** [comment] 2019-11-21 20:36
duplicate of https://github.com/tuskyapp/Tusky/issues/1337

**Closed by connyduck** 2019-11-21 20:36 UTC
