### ISSUE TITLE
[Design review] Accessibility of item_status buttons

### ISSUE THREAD

**Issue by objcode** [tuskyapp/Tusky#2859] opened 2022-11-19 06:01 UTC
The touch target for the buttons on item status is a bit small.

This issue was reproduced by myself by clicking the button imprecisely. It was easy to have missed clicks that landed in the margin between buttons.

Checking the Accessibilty guide for buttons like this, it recommends 48dp by 48dp with 8dp gap between touch targets. In item_status, the buttons are 30dp by 30dp with 8dp gap between touch targets.

Relevant code: https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/res/layout/item_status.xml#L349  (and the other item_status)

Looking at the design and code, it appears that a design change is necessary to increase the touch target. As a result, I'm opening an issue for further discussion (don't want to open a CL with a drive-by design change :) ).

This issue came from a toot thread here: https://mastodon.gamedev.place/@SpewanMcGregor/109368140489893305

* * * *
- Tusky Version: tip of tree (repro on 19.0)
- Android Version: Android T (QPR1)
- Android Device: Pixel 6
- Mastodon instance (if applicable): http://tech.lgbt (not relevant to bug)

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2022-11-21 13:22
Duplicate of #2825

**Closed by charlag** 2022-11-21 13:22 UTC
