### ISSUE TITLE
show full size image in timeline

### ISSUE THREAD

**Issue by lucamp** [tuskyapp/Tusky#2347] opened 2022-02-19 13:05 UTC
Hi,
it would be nice to have an option that allows to show full size images in the timeline as mastodon web interface does. This way the user do not have to open it every time to see it, it's really useful if you follow pixelfed accounts.

* * * *
- Tusky Version: 15.1 fdroid
- Android Version: 10

**Comment by connyduck** [comment] 2022-03-01 19:52
duplicate of https://github.com/tuskyapp/Tusky/issues/1995

**Closed by connyduck** 2022-03-01 19:52 UTC
