### ISSUE TITLE
Emoji categories not shown

### ISSUE THREAD

**Issue by SleepyCatten** [tuskyapp/Tusky#3437] opened 2023-03-12 12:30 UTC
Emoji can be assigned named categories on Mastodon, which groups them together. However, the emoji categories are not shown by Tusky. Instead, the emojis across all categories seem to be shown in alphabetical order.

* * * *
- Tusky Version: 21.0
- Android Version: 13
- Android Device: Galaxy S20 FE 5G
- Mastodon instance (if applicable): cultofshiv.wtf

- [✅] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2023-03-12 14:20
duplicate of https://github.com/tuskyapp/Tusky/issues/1868

**Closed by connyduck** 2023-03-12 14:20 UTC
