### ISSUE TITLE
This post is too gay causing a crash (IllegalArgumentException: width and height must be > 0)

### ISSUE THREAD

**Issue by MinekPo1** [tuskyapp/Tusky#4293] opened 2024-02-28 21:51 UTC
### Detailed description

tbh its probably the emoji being funny but idk

### Steps to reproduce the problem

1. open https://fedi.catboy.agency/notes/9q9u3nwjd8hd03wx

### Debug information

Tusky 24.1  Device:  motorola moto e22 Android version: 12 SDK version: 31  Account:  @minekpo1@tilde.zone Version: 4.3.0-alpha.3+glitch

<details>
<summary>full logcat trace</summary>

```
FATAL EXCEPTION: FrameDecoderExecutor-1
Process: com.keylesspalace.tusky, PID: 4875
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1095)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1062)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1012)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:973)
	at com.github.penfeizhou.animation.decode.e.l(SourceFile:65)
	at x6.l.p(SourceFile:149)
	at com.github.penfeizhou.animation.decode.e.r(SourceFile:48)
	at com.github.penfeizhou.animation.decode.b.run(SourceFile:50)
	at com.github.penfeizhou.animation.decode.e.i(SourceFile:81)
	at com.bumptech.glide.manager.q.run(SourceFile:89)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

</details>

**Comment by Tak** [comment] 2024-02-29 07:35
😐 I can't reproduce this on Tusky 24 nor nightly (pixel 2xl android 11, emulator android 12) - maybe something was fixed on the source instance?

**Comment by MinekPo1** [comment] 2024-02-29 17:49
weird, though I believe I can confirm it is the emoji (specifically `:FelixPeek:` from fedi.catboy.agency , though it originates from [mraww.catboy.download](https://mraoow.catboy.download/catboyagency//catboyagency/648a315a-c27d-4893-9ed4-4e2257651058.webp)), as [this post](https://fedi.catboy.agency/notes/9qb2i1trd8hd0635) also triggers the crash for me.

is there anything I could do to help yall find the glitch? I might be able to analyse that .webp image, though I unfortunately cannot promise to do that.

**Comment by connyduck** [comment] 2024-02-29 17:55
I can reproduce. Probably another bug in the apng library. Maybe we need to look for another library, there are so many problem recently :/
@Tak do you have "animate custom emojis" on?

**Comment by MinekPo1** [comment] 2024-02-29 17:57
> I can reproduce. Probably another bug in the apng library. Maybe we need to look for another library, there are so many problem recently :/
> @Tak do you have "animate custom emojis" on?

it crashed with animate custom emojis off for me, though I have not restated the app between changing the setting and loading the post

**Closed** 2024-12-22 11:53 UTC
Labels: bug
