### ISSUE TITLE
Images not loading (avatars and media)

### ISSUE THREAD

**Issue by Vavassor** [tuskyapp/Tusky#198] opened 2017-04-18 23:46 UTC
This has been reported to me on Mastodon.

Since everything but images loads fine it's definitely related to usage of Picasso. It seems to be only a few devices are affected.
-2 reports on blackberry devices (which use an android runtime in Blackberry OS)
-one on a Samsung S3 mini with Android 4.1
-another on a OnePlus 3T with LineageOS
It's not yet clear if it's ALSO instance-dependent or just device-dependent.

**Edit:** The person on the OnePlus 3T tried it on two instances and one works, but the other does not. So it IS instance dependent.

**Comment by PeterCxy** [comment] 2017-04-22 03:59
It failed with `com.squareup.picasso.Downloader$ResponseException: 502 Bad Gateway`, but the URL to load is correct and can be loaded both from browser and from curl.

**Comment by PeterCxy** [comment] 2017-04-22 04:13
It fails only with certain domains, for example, https://files.mastodon.social/media_attachments/files/000/301/159/original/a1ac4893e3857c22.jpg works greatly with Picasso while https://bucket.angry.im/mastodon/media_attachments/files/000/001/970/small/d35e0d0cf8c34c79.jpg does not work at all with PIcasso, with the 502 error. But it loads happily with browser and with curl.

**Comment by PeterCxy** [comment] 2017-04-22 04:45
Replacing `Picasso` with `Glide` did nothing to resolving the problem. Seems like a deeper problem...

**Comment by PeterCxy** [comment] 2017-04-22 04:51
The good news is using `OkHttp3Downloader` magically fixes this problem.

**Comment by Vavassor** [comment] 2017-04-22 04:54
@PeterCxy Weird? I thought it used OkHttp3Downloader by default if you didn't specify one?

**Comment by PeterCxy** [comment] 2017-04-22 05:18
I've submitted a Pull Request on this.

**Comment by jgbresson** [comment] 2017-05-11 23:56
I'm using an LG G6 on Android 7.0 and Tusky 1.1.3 and no media seems to be loading for me.

**Comment by Strubbl** [comment] 2017-06-15 21:48
I am on latest F-droid version app's version (1.1.3) and on mastodon instance social.tchncs.de. Same issue here

**Comment by Strubbl** [comment] 2017-06-18 20:01
Okay, i had a look into logcat. Looks like an SSL issue. Some lines from the log

```
06-18 21:58:17.105 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R0] Request{https://social.tchncs.de/headers/original/missing.png resize(608,192) centerCrop}
06-18 21:58:17.114 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R1] Request{https://social.tchncs.de/system/accounts/avatars/000/049/304/original/c8b2b32823074a41.jpeg?1496522727}
06-18 21:58:17.115 13482-13482/com.keylesspalace.tusky I/MaterialDrawer: You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
06-18 21:58:17.115 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  enqueued     [R0]+11ms 
06-18 21:58:17.118 13482-15380/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R0]+14ms 
06-18 21:58:17.119 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  enqueued     [R1]+3ms 
06-18 21:58:17.121 13482-15381/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R1]+7ms 
06-18 21:58:17.596 13482-13489/com.keylesspalace.tusky I/art: Do partial code cache collection, code=54KB, data=61KB
06-18 21:58:17.597 13482-13489/com.keylesspalace.tusky I/art: After code cache collection, code=54KB, data=61KB
06-18 21:58:17.597 13482-13489/com.keylesspalace.tusky I/art: Increasing code cache capacity to 256KB
06-18 21:58:17.718 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R0]+614ms 
06-18 21:58:17.720 13482-15392/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R0]+615ms 
06-18 21:58:17.729 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R1]+615ms 
06-18 21:58:17.733 13482-15393/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R1]+618ms 
06-18 21:58:18.145 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R2] Request{https://social.tchncs.de/system/accounts/avatars/000/023/788/original/c4c287a5f9d91a31.jpg?1491856936 rounded}
06-18 21:58:18.148 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  enqueued     [R2]+3ms 
06-18 21:58:18.152 13482-15380/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R2]+5ms 
06-18 21:58:18.165 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R3] Request{https://social.tchncs.de/system/accounts/avatars/000/008/506/original/9ed6bb84787343b9.jpg?1491404579 rounded}
06-18 21:58:18.166 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  enqueued     [R3]+0ms 
06-18 21:58:18.166 13482-15381/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R3]+1ms 
06-18 21:58:18.187 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R4] Request{https://social.tchncs.de/system/accounts/avatars/000/043/712/original/1-original-20170501180753.jpeg?1493656533 rounded}
06-18 21:58:18.190 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  enqueued     [R4]+2ms 
06-18 21:58:18.191 13482-15392/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R4]+3ms 
06-18 21:58:18.200 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R5] Request{https://social.tchncs.de/system/accounts/avatars/000/009/696/original/404f7baf97baf738.jpeg?1491567963 rounded}
06-18 21:58:18.201 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  enqueued     [R5]+0ms 
06-18 21:58:18.202 13482-15393/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R5]+1ms 
06-18 21:58:18.212 13482-13482/com.keylesspalace.tusky D/Picasso: Main        created      [R6] Request{https://social.tchncs.de/system/accounts/avatars/000/009/696/original/404f7baf97baf738.jpeg?1491567963 rounded}
06-18 21:58:18.213 13482-13530/com.keylesspalace.tusky D/Picasso: Hunter      joined       [R6]+0ms to [R5]+12ms, [R6]+0ms
06-18 21:58:18.309 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R0]+1204ms 
06-18 21:58:18.310 13482-15380/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R0]+1205ms 
06-18 21:58:18.313 13482-13482/com.keylesspalace.tusky I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c1156e2 time:58468535
06-18 21:58:18.318 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  batched      [R0]+1214ms for error
06-18 21:58:18.325 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R1]+1210ms 
06-18 21:58:18.326 13482-15381/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R1]+1212ms 
06-18 21:58:18.332 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  batched      [R1]+1217ms for error
06-18 21:58:18.521 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  delivered    [R0]+1415ms, [R1]+1406ms 
06-18 21:58:18.522 13482-13482/com.keylesspalace.tusky D/Picasso: Main        errored      [R0]+1417ms 
06-18 21:58:18.523 13482-13482/com.keylesspalace.tusky W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
06-18 21:58:18.530 13482-13482/com.keylesspalace.tusky W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
06-18 21:58:18.530 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
06-18 21:58:18.530 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
06-18 21:58:18.530 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
06-18 21:58:18.530 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.531 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-18 21:58:18.532 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
06-18 21:58:18.532 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.532 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
06-18 21:58:18.532 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.532 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at com.jakewharton.picasso.OkHttp3Downloader.load(OkHttp3Downloader.java:136)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-18 21:58:18.533 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-18 21:58:18.534 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-18 21:58:18.534 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-18 21:58:18.534 13482-13482/com.keylesspalace.tusky W/System.err:     at java.lang.Thread.run(Thread.java:761)
06-18 21:58:18.534 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-18 21:58:18.535 13482-13482/com.keylesspalace.tusky W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7f595ecdc0: Failure in SSL library, usually a protocol error
06-18 21:58:18.535 13482-13482/com.keylesspalace.tusky W/System.err: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x7f582d9320:0x00000001)
06-18 21:58:18.535 13482-13482/com.keylesspalace.tusky W/System.err: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x7f686e1f76:0x00000000)
06-18 21:58:18.535 13482-13482/com.keylesspalace.tusky W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-18 21:58:18.535 13482-13482/com.keylesspalace.tusky W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
06-18 21:58:18.535 13482-13482/com.keylesspalace.tusky W/System.err: 	... 29 more
06-18 21:58:18.540 13482-13482/com.keylesspalace.tusky D/Picasso: Main        errored      [R1]+1422ms 
06-18 21:58:18.541 13482-13482/com.keylesspalace.tusky W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
06-18 21:58:18.541 13482-13482/com.keylesspalace.tusky W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
06-18 21:58:18.541 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
06-18 21:58:18.541 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
06-18 21:58:18.541 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
06-18 21:58:18.541 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at com.jakewharton.picasso.OkHttp3Downloader.load(OkHttp3Downloader.java:136)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
06-18 21:58:18.542 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at java.lang.Thread.run(Thread.java:761)
06-18 21:58:18.543 13482-13482/com.keylesspalace.tusky W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
06-18 21:58:18.544 13482-13482/com.keylesspalace.tusky W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x7f6ce3ce00: Failure in SSL library, usually a protocol error
06-18 21:58:18.544 13482-13482/com.keylesspalace.tusky W/System.err: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x7f6ce56180:0x00000001)
06-18 21:58:18.544 13482-13482/com.keylesspalace.tusky W/System.err: error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x7f686e1f76:0x00000000)
06-18 21:58:18.544 13482-13482/com.keylesspalace.tusky W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
06-18 21:58:18.545 13482-13482/com.keylesspalace.tusky W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
06-18 21:58:18.545 13482-13482/com.keylesspalace.tusky W/System.err: 	... 29 more
06-18 21:58:18.735 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R2]+589ms 
06-18 21:58:18.738 13482-15392/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R2]+592ms 
06-18 21:58:18.764 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R3]+598ms 
06-18 21:58:18.766 13482-15404/com.keylesspalace.tusky D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.paho58466206094636
06-18 21:58:18.766 13482-15393/com.keylesspalace.tusky D/Picasso: Hunter      executing    [R3]+600ms 
06-18 21:58:18.774 13482-15404/com.keylesspalace.tusky D/AlarmPingSender: Schedule next alarm at 1497815958773
06-18 21:58:18.776 13482-15404/com.keylesspalace.tusky D/AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 60000
06-18 21:58:18.781 13482-13530/com.keylesspalace.tusky D/Picasso: Dispatcher  retrying     [R4]+593ms 
```

**Comment by Strubbl** [comment] 2017-06-18 20:14
Looks like this issue https://issuetracker.google.com/issues/37122132
Sony does not provide an update to Android 7.1.1 :( 

Can you fix this somehow?

**Comment by Vavassor** [comment] 2017-06-18 20:51
That log seems to indicate it's essentially the same problem as Issue #46. I was able to partially solve that one for requests made to the Mastodon API for servers that don't **require** these elliptic curves but simply _prefer_ them. The connections made by Picasso go through a different route, so they do not use my fix. Basically, it uses a modified ```OkHttpClient``` that enables a broader set of connection parameters and goes through several steps of fallback. It looks like there's a constructor for ```OkHttpDownloader``` that accepts a ```OkHttpClient```, so it may be just as easy as passing my modified client to it.

I've mentioned it in that issue, but I don't have an actual Android 7.0 test environment working, so I'll have to get someone else to verify what I do actually works.

**Comment by Strubbl** [comment] 2017-06-19 11:29
@Vavassor Thank you, the referenced commit fixes my image loading/SSL problem.
Any yes, #46 looks like my issue. Sorry for referencing it here.

**Comment by JORGETECH** [comment] 2017-07-03 16:21
Will this be fixed in the next update?

**Comment by charlag** [comment] 2017-11-06 19:04
@Strubbl @JORGETECH @jgbresson @PeterCxy can anyone test it on the 1.2 please?

**Comment by Strubbl** [comment] 2017-11-06 19:15
I am using version 1.2.1 and the issue is gone.

**Comment by charlag** [comment] 2017-11-06 19:20
@Strubbl I'm glad to hear that, thank you!

**Comment by orbifx** [comment] 2017-11-06 21:56
Media seems to load now.

**Comment by johnnagro** [comment] 2017-11-22 03:14
I think I am experiencing the same issue, Tusky 1.3.1, Android 7 (Moto) 
![screenshot_20171121-221147](https://user-images.githubusercontent.com/31442/33108228-395d9e22-cf09-11e7-892d-55d28de97349.png)

**Comment by Strubbl** [comment] 2017-11-22 10:50
@johnnagro you have avatars on your screenshot. That's not the issue.
Maybe the hill just does not have an avatar set

**Comment by charlag** [comment] 2017-11-22 11:32
I have experienced similar problems recently, avatars/pictures just don't load at random (but they do through web)

**Comment by johnnagro** [comment] 2017-11-22 17:42
@Strubbl those avatars work on the web, random other avatars do not work like @charlag suggested. it may be a different problem entirely from this issue but I wanted to document the issue.

**Comment by connyduck** [comment] 2017-11-23 21:58
This also affects custom emojis it seems. Logcat says, Server returned 403. But how on earth can this be, avatars and emojis do not require any authentication & they load fine in browser?

**Comment by connyduck** [comment] 2017-11-27 16:00
It is a server issue as @Gargron confirmed.
We shoud add a workaround by ignoring the status code though.

**Closed** 2018-03-05 15:17 UTC
Labels: bug
