### ISSUE TITLE
Show that a post is part of a thread

### ISSUE THREAD

**Issue by fdmarcin** [tuskyapp/Tusky#3771] opened 2023-06-23 14:24 UTC
Hi! Thanks for creating Tusky!

I'd love it if toots in the timeline showed that they're part of a thread. Currently they are presented in the feed in the same way as standalone posts, and you don't know that you're missing the context.

This is how it looks in the Megalodon app:

![timeline in the Megalodon app](https://github.com/tuskyapp/Tusky/assets/25668969/84f7e5e2-abc4-45df-8ac3-fc70daf0dc22)

* * * *
- Tusky Version: 22.0
- Android Version: 11
- Android Device: N/A
- Mastodon instance (if applicable): N/A

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2023-06-26 14:57
That is not true, If a post is a reply ("part of a thread"), it has a double arrow as the reply icon. If there arre replies, they are indicated with a number next to that icon. 
But yes this situation can be improved.

**Comment by connyduck** [comment] 2023-06-26 14:58
Duplicate of https://github.com/tuskyapp/Tusky/issues/1469

**Closed by connyduck** 2023-06-26 14:58 UTC
