### ISSUE TITLE
Setting a image caption (description for the visually impaired) crashes the app

### ISSUE THREAD

**Issue by kingannoy** [tuskyapp/Tusky#2183] opened 2021-05-29 21:40 UTC
Presumably after a recent update the image description feature has stopped working. The feature has worked for me in the past. Downgrading to a older version doesn't seem to work via F-Droid. 

Opening the window to start typing a image description reliably crashes Tusky. The window does open, but after about half a second the app crashes.

Usually I set the caption after writing a toot. That Toot's text is lost after the crash. This is _really_ annoying.

* * * *
- Tusky Version: 15.0
- Android Version: 8.1.0
- Android Device: moto G5 plus
- Mastodon instance (if applicable): octodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

Edited to add:

I figured out how to get crashlogs to show. I hope this helps 😃
[crashlog.txt](https://github.com/tuskyapp/Tusky/files/6565388/crashlog.txt)

**Comment by charlag** [comment] 2021-05-30 08:45
We are very sorry about that, see #2180

duplicate of #2180

**Closed by charlag** 2021-05-30 08:45 UTC
