### ISSUE TITLE
[Feature Request] Toot Notifications

### ISSUE THREAD

**Issue by MrTeeXD** [tuskyapp/Tusky#1573] opened 2019-11-26 17:56 UTC
I don't see an option to recieve notifications when someone sends a toot and i get really bored when opening the app and refreshing everytime so this might be a great feature to have.

* * * *
- Tusky Version: 9.1
- Android Version: Android 9
- Android Device: Huaweii P Smart
- Mastodon instance (if applicable): Mastodon.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-12-04 20:49
@MrTeeXD so you want a notification for *every* post in your timeline?
That's quite specific

**Comment by MrTeeXD** [comment] 2019-12-04 20:51
Yes

**Comment by charlag** [comment] 2020-01-18 22:14
Duplicate of #290

**Closed by charlag** 2020-01-18 22:14 UTC
