### ISSUE TITLE
Feature Request: Code blocks

### ISSUE THREAD

**Issue by marek22k** [tuskyapp/Tusky#4033] opened 2023-09-25 19:00 UTC
Hello,

sometimes I like to reply to toots with code. To format it correctly (e. g. with monospace) you often use '`' (or three '`' for multi-line code). This can be done in Markdown and Telegram for example. I would like Tusky to recognize such code blocks and display them with monospace for example.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2023-09-26 06:53
Duplicate of #1840

**Closed by Tak** 2023-09-26 06:53 UTC

**Comment by marek22k** [comment] 2023-09-26 08:17
My feature request is only for Code Blocks and not for Markdown. Therefore this is not a duplicate.
