### ISSUE TITLE
improve presentation of block quotes in markdown messages

### ISSUE THREAD

**Issue by jubalfh** [tuskyapp/Tusky#3101] opened 2022-12-24 02:35 UTC
Note: it's not a bug of tusky, but more of a feature request, and the scope is only *presentation*, not creation or edition of markdown messages.

Right now Tusky provides rudimentary styling for markdown messages which is mostly readable and just good enough – especially for inline elements (but the headings are good too).

The block quote marker though is rendered with a thin vertical dark blue line with almost no padding, and it would gain very much if it was given more distinctive styling.

Even very limited changes – making the line thicker, rendering it using the same color as the text, and adding padding (especially between the vertical line and the rendered text) would greatly improve readability and provide a good visual hint differentiating between regular and quoted text.

* * * *
- Tusky Version: 20
- Android Version: not relevant
- Android Device: not relevant
- Mastodon instance (if applicable): not relevant

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2022-12-24 07:56
duplicate of https://github.com/tuskyapp/Tusky/issues/1271

**Closed by connyduck** 2022-12-24 07:56 UTC
