### ISSUE TITLE
Some links are not highlighted and clickable

### ISSUE THREAD

**Issue by kyori19** [tuskyapp/Tusky#1032] opened 2019-02-08 13:42 UTC
LinkHelper's behavior is something weird.
Some `<a>` tags seems to be ignored when convert HTML to Spannable.
For example...
- Mention from misskey instance. (*1)
- Links which is modified its text by using markdown (I used Misskey for testing). (*2)
- Links which have bracket (`]` or `)`) in end of it. (*3)

*1
![image](https://user-images.githubusercontent.com/27999567/52480928-71a07f80-2bf0-11e9-8d18-eb0f64edfb67.png)
[misskey.xyz(sender)](https://misskey.xyz/notes/5c5d79e3a5dde1002a17cb01)
same post from [odakyu.app(receiver)](https://odakyu.app/@ars42525/101556543893086801)

*2
![image](https://user-images.githubusercontent.com/27999567/52480841-27b79980-2bf0-11e9-8559-e034843ffe6f.png)
[misskey.xyz(sender)](https://misskey.xyz/notes/5c5d812b6dfac900287ab6cd)

*3
![image](https://user-images.githubusercontent.com/27999567/52480834-225a4f00-2bf0-11e9-91d5-4d4e090ad8aa.png)
[odakyu.app(sender)](https://odakyu.app/@ars42525/101556680496777349)

* * * *
- Tusky Version: 4.1 #d5173c2
- Android Version: 8.0.0
- Android Device: Sony Xperia XZ1 Compact (G8441)
- Mastodon instance (if applicable): odakyu.app, mstdn.jp

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-02-09 20:00
Thanks for reporting, this is quite serious
@Tak mind looking at it? I checked it and found out that non-strict regex considers closing `]` to be a part of the url but strict one doesn't so it doesn't end up well obviously
(maybe we just shouldn't remove all URL spans?)
@connyduck I think this must be fixed before the next release

**Comment by charlag** [comment] 2019-02-09 20:01
To be more precise and save some time it's inside `highlightSpans()`

**Comment by Tak** [comment] 2019-02-10 08:10
I'll take a look when I get a chance.
If we're receiving already-marked-up content where information is missing from the text, then I guess we need to preserve the original spans.
If this is causing serious regressions, we can back out the `expand-url-schemes` merge (a minor enhancement at best) until it can be reworked.

**Comment by charlag** [comment] 2019-02-11 05:44
Broken hashtag:
https://social.coop/@GuerillaOntologist/101570655919228332

I can't remember why we're doing search ourselves in the first place (at least for TL) and I think that maybe we should preserve markup there. When composing it's out domain, obviously.

**Comment by Tak** [comment] 2019-02-11 07:12
Hm, this one is because it's not detecting the emoji as a word break - so "😀🐐#thing" might as well be "xx#Thing"

**Comment by connyduck** [comment] 2019-02-11 07:44
> @connyduck I think this must be fixed before the next release

Yes definitely. Should I revert the commit in question?

**Comment by charlag** [comment] 2019-02-11 07:50
That's the quickest option perhaps, we can come back to it after the release.

**Comment by connyduck** [comment] 2019-02-11 14:41
https://github.com/tuskyapp/Tusky/commit/eeaadea905975a37742b09c0835b693b0a9be7f0

**Closed by connyduck** 2019-02-11 14:41 UTC
Labels: bug
