### ISSUE TITLE
Media in CW aren't hidden

### ISSUE THREAD

**Issue by Ph4ntomas** [tuskyapp/Tusky#547] opened 2018-03-09 21:30 UTC
Hi,

I found out that when a media is sent in a message with a CW, Tusky show it anyway.

Is there a way to at least ask confirmation (I think that's how the webUI handle this), or to display the image in the hidden drawer ?

I'm using Tusky 1.5.2 on Android 8.0.0

**Comment by charlag** [comment] 2018-03-10 12:18
Hi, thanks for reporting!
Could you please elaborate on this? I'm not quite sure what you mean. When there's a post in the timeline with the CW and media is shown?

**Comment by Ph4ntomas** [comment] 2018-03-10 17:05
Sure, here is two picture, one is a screenshot from my phone,  the other from my computer.

As you can see, Tusky does not hide the picture as it should, and same goes for others media afaik.

(What I haven't tried : I don't know if Tusky ignore the NSFW tag on all medias, or just on the one in CW drawers)

![Via TuskyApp](https://user-images.githubusercontent.com/23215826/37244672-a4bb8c6e-245a-11e8-9aa0-8ca1b315a67f.jpg)
![Via Web UI](https://user-images.githubusercontent.com/23215826/37244680-b782b340-245a-11e8-96d1-5f59f8e27044.png)

**Comment by Ph4ntomas** [comment] 2018-03-10 17:06
Uh, sorry for the picture size, never thought it would be that big

**Comment by charlag** [comment] 2018-03-10 17:59
Thanks! Nvm the size.
I'm not sure why it's happening - I've just posted a picture with a cw and it works like it should 🤔

**Comment by Ph4ntomas** [comment] 2018-03-10 20:40
Oh, that's weird

Just saw that I forgot infos on the device : 
I have a OnePlus 3T running OxygenOS 5.0.1 (Which is based on Android 8.0.0), 
on which I disabled most google services (from settings/apps)

Well, I'll try to troubleshoot this on my end, but I don't have time atm :/

**Comment by Ph4ntomas** [comment] 2018-03-10 20:58
Uh, I found how to fix it.

I'll need a dev env to try to reproduce it tho, but it seems that something went wrong during the update (I guess). 

Anyway, clearing the cache did not work, but wiping local data did the trick. Still I don't know why tho :/

**Comment by connyduck** [comment] 2018-04-14 06:44
Maybe you had the "always show Nsfw media" option on? Anyway, can't reproduce, closing.

**Closed by connyduck** 2018-04-14 06:44 UTC
