### ISSUE TITLE
[Bug] Bullet points in quote render outside of the quote

### ISSUE THREAD

**Issue by frereit** [tuskyapp/Tusky#4233] opened 2024-01-20 21:12 UTC
Any toot with bullet points inside a quote, the bullet points are rendered before the quote line.

For example:

```
> this is a test
> - point 1
> - point 2
```

![Screenshot_20240120_215609_Tusky.png](https://github.com/tuskyapp/Tusky/assets/18506129/c8196eab-52f4-4cd9-9fb9-4a1186762758)

**Comment by connyduck** [comment] 2024-01-28 18:03
duplicate of https://github.com/tuskyapp/Tusky/issues/4163

**Closed by connyduck** 2024-01-28 18:03 UTC
