### ISSUE TITLE
[Feature Request] Change the Toot button to Post or Publish

### ISSUE THREAD

**Issue by SeaGriff** [tuskyapp/Tusky#2839] opened 2022-11-16 02:57 UTC
Toot is no longer the 'official' terminology and the word is quite off-putting.

**Comment by scottiefalkon** [comment] 2022-11-16 08:21
Agreed. It needs to be changed.

**Comment by Tak** [comment] 2022-11-16 10:49
Duplicate of #2791

**Closed** 2022-11-20 08:10 UTC
