### ISSUE TITLE
Specific notification in the notification page crashes the app

### ISSUE THREAD

**Issue by firnen0** [tuskyapp/Tusky#1701] opened 2020-02-18 21:35 UTC
If you scroll down along the right edge on the notification page, the app will crash.
* * * *
- Tusky Version: 9.1
- Android Version: 10
- Android Build: Oxygen OS 10.0.7HD65AA
- Android Device: OnePlus 7t

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by firnen0** [comment] 2020-02-18 21:37
It appears to always happen when a specific notification is shown.

**Comment by charlag** [comment] 2020-02-18 22:54
Hi
It's 99% your instance doing something funny with notifications. That's why we ask for the instance (or at least software)

**Comment by firnen0** [comment] 2020-02-19 00:07
I was not aware, my instance is dragon.style

**Comment by charlag** [comment] 2020-02-19 00:09
Thanks. If you find out what's special about it or if you can get a crash log, please tell us.

**Comment by firnen0** [comment] 2020-02-19 00:15
I don't seem to be able to copyfrom the stack trace, but I have a screenshot of it.
![Screenshot_20200218-191415](https://user-images.githubusercontent.com/37234915/74789519-fea9fa00-5282-11ea-80da-ca78bc02af70.jpg)

**Comment by charlag** [comment] 2020-02-19 07:34
Thanks. Seems like one of the fields is null. Can you please check nightly or beta, I think we might have fixed that?

**Comment by connyduck** [comment] 2020-02-19 20:19
I am pretty sure this is a duplicate of https://github.com/tuskyapp/Tusky/issues/1578

**Comment by firnen0** [comment] 2020-02-19 20:24
Or the bug is just coming back

**Comment by connyduck** [comment] 2020-02-19 20:26
The fix has not been released, thats why @charlag asked you to try nightly or beta. If it doesn't crash there its a duplicate of #1578, otherwise its something else.

**Comment by firnen0** [comment] 2020-02-19 21:21
This still hapens on nightly, but the notification this happens on has changed, possibly because I got some more notifications since last testing. The notification that causes that has changed for both nightly and release. I've attached the stack trace from nightly.
![2020-2-19_16-17-43](https://user-images.githubusercontent.com/37234915/74877678-d5957200-5333-11ea-9558-6b9719649150.PNG)

**Comment by connyduck** [comment] 2020-05-29 15:38
Can you still reproduce that? @firnen0

**Comment by charlag** [comment] 2022-05-10 20:47
Closing due to inactivity

**Closed by charlag** 2022-05-10 20:47 UTC
