### ISSUE TITLE
Tusky doesn't remember SAML account logins

### ISSUE THREAD

**Issue by kornysietsma** [tuskyapp/Tusky#2462] opened 2022-04-27 14:29 UTC
If I add an instance with a SAML login, such as toot.thoughtworks.com, Tusky goes through the authentication process but then loads the instance in a browser window not in the app - see screenshot.

![Screenshot_20220427-152316](https://user-images.githubusercontent.com/17765/165541773-013e8aed-77d2-49c4-b3fe-4c79e869d397.png)

The new instance is not added to Tusky, if I press the left arrow, or quit and re-run Tusky, it does not show the new instance as an option.

* * * *
- Tusky Version: 17.0

- Android Version: 11
- Android Device: Pixel 2
- Mastodon instance (if applicable): toot.thoughtworks.com

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2022-04-27 16:15
This is very weird, thanks for reporting. I think I'll need a SAML login on some instance in order to debug this, what is the easiest way to do that?

**Comment by jz8132543** [comment] 2022-05-05 07:31
I also find it strange that I can log in probabilistically.

**Comment by jz8132543** [comment] 2022-05-11 06:29
> This is very weird, thanks for reporting. I think I'll need a SAML login on some instance in order to debug this, what is the easiest way to do that?

I had the same problem, but I'm using OpenID. I can provide you with an account and provide my profile, hopefully the issue will be resolved.Thank you for your attention to this issue!

**Comment by Steffo99** [comment] 2022-05-22 10:35
I have the same problem, and I can provide a SAML login and example instance to @connyduck if needed.

**Comment by connyduck** [comment] 2022-05-22 12:24
Yes please tusky@connyduck.at @Steffo99

**Comment by Steffo99** [comment] 2022-05-22 13:58
@connyduck I've sent you the credentials! Thanks in advance for your time :)

**Comment by connyduck** [comment] 2022-05-22 15:48
Thanks, I can reproduce it and I think it is an issue with Mastodon itself since it also occurs in other apps https://github.com/mastodon/mastodon/issues/18481

**Comment by Steffo99** [comment] 2022-05-22 15:55
Strangely enough, I've been able to login with all the other apps, so there must be something strange going on...

**Comment by Steffo99** [comment] 2022-05-22 15:59
I'm trying to debug the issue as well, and managed to reproduce the problem even on a desktop browser.

I'm trying to understand what the official Mastodon app does during login which Tusky does not.

https://github.com/mastodon/mastodon-android/blob/master/mastodon/src/main/java/org/joinmastodon/android/OAuthActivity.java

So far, I haven't been able to spot any difference...

**Comment by connyduck** [comment] 2022-05-22 16:02
Mastodon for Android opens your browser and if you are logged into the browser you don't need to go through the SAML flow.
Tusky on the other hand uses a WebView.

**Comment by Steffo99** [comment] 2022-05-22 16:04
Ooh, that makes sense!

Yeah, it's definitely a backend bug then.

I'll go look into that, thanks for your help!

**Comment by decentral1se** [comment] 2022-06-06 09:02
Just to chime in, thanks for the triage labour, we ran into this as well, hometown 3.4.6 + tusky v17/18. We ended up recommending folks to use subway tooter/husky for now. But curiously, there is a work-around required for husky, you need to log in via the browser first, then the app, and it work. This issue is really strange since we didn't update our hometown code at all and older versions of tusky still have this issue (until v16 i think?). So, maybe some other moving part in the ecosystem is causing it? Somewhere in the masto rails stack, idk...

**Comment by charlag** [comment] 2022-06-06 09:08
We switched to WebView but probably Husky didn't?

**Comment by rscmbbng** [comment] 2022-08-29 07:18
Can confirm this issue with OpenID Connect, would be great to have a resolution. This used to work on older versions of Tusky. How can we help solve this issue?

**Comment by connyduck** [comment] 2022-08-29 10:14
We could switch back to browser redirects but that would suck for a lot of other reasons. Ideally it gets fixed on Mastdon's side.

**Comment by Steffo99** [comment] 2022-08-29 16:10
I'd agree it would be better for it to be fixed on Mastodon's side, this bug also causes problems with remote follows and some other actions while not logged in.

**Comment by mashedkeyboard** [comment] 2022-10-29 08:35
Ideally, I'd like for there to be an option to have the browser redirect anyway. The simple reason is that the WebView doesn't support WebAuthn authentication, and signing in to my oAuth provider that my Mastodon instance uses requires one - so I can't sign in to Tusky at all, because there's no way to actually get the 2FA in place at the moment.

**Comment by vranki** [comment] 2022-11-22 19:50
The same happens for me, using Authentik as SSO provider. I can provide test account to our instance if needed.

**Comment by Tak** [comment] 2023-02-14 09:17
Workaround added in #3165

**Closed by Tak** 2023-02-14 09:17 UTC
