### ISSUE TITLE
Crash when going to the notification tab

### ISSUE THREAD

**Issue by AnaGelez** [tuskyapp/Tusky#1441] opened 2019-08-05 10:58 UTC
Hello. Since a few days, when I try to go to the notifications tab in Tusky, the app crashes after one or two seconds. I tried to clear my notifications in case one of them was causing the issue, but it didn't helped… Here is what my phone's crash reporter says, if it helps:

![Screenshot_2019-08-05-12-51-35-754_com miui bugreport](https://user-images.githubusercontent.com/16254623/62459624-2f5f9180-b780-11e9-8591-cf206ebf8a4f.png)

* * * *
- Tusky Version: 8.1
- Android Version: 9
- Android Device: Xiaomi Mi 8
- Mastodon instance (if applicable): soc.punktrash.club (Pleroma)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2019-08-05 14:39
Duplicate of #1398
(tl,dr: its a bug in Pleroma)

**Closed by connyduck** 2019-08-05 14:39 UTC

**Comment by AnaGelez** [comment] 2019-08-05 14:51
Oh, sorry, I didn't see this issue. Thank you for the information!
