### ISSUE TITLE
Hiding the top bar disables the side menu

### ISSUE THREAD

**Issue by icexleo** [tuskyapp/Tusky#2481] opened 2022-04-29 20:12 UTC
When enabling "Hide the title of the top toolbar" in Preferences you can no longer access the menu.

* * * *
- Tusky Version: 17.0
- Android Version: Android 11 / EMUI 12
- Android Device: Huawei P40 Pro
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2022-04-30 09:13
You can long-press the side of the screen and the menu will open.

Duplicate of https://github.com/tuskyapp/Tusky/issues/2473 where there is more info

**Closed by connyduck** 2022-04-30 09:13 UTC
