### ISSUE TITLE
Filters do not work on Home timeline

### ISSUE THREAD

**Issue by shegeman** [tuskyapp/Tusky#1380] opened 2019-07-10 22:37 UTC
My filters don't seem to be working to filter on my home timeline on Tusky, while they do work perfectly on the default Masto web client. See screenshots.

* * * *
- Tusky Version: 8.0
- Android Version: 9
![FilteredTerms](https://user-images.githubusercontent.com/2636610/61009716-83fe2100-a328-11e9-9378-3801fcc81798.png)
![mastoWebClientFilterWorks](https://user-images.githubusercontent.com/2636610/61009717-83fe2100-a328-11e9-9f8b-8e13d7608dc9.png)
![TuskyFilterNotApplied](https://user-images.githubusercontent.com/2636610/61009718-83fe2100-a328-11e9-9e5c-5a1f7d07fbcb.png)

- Android Device: Pixel 2
- Mastodon instance (if applicable): birb.site

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JuanjoSalvador** [comment] 2019-07-11 09:42
So, the filters on the website are not applicable on Tusky app, isn't it?

**Comment by shegeman** [comment] 2019-07-11 15:27
As demonstrated in the first screenshot, which was taken in Tusky, the filters are an Account Preference. They apply in both the website and the app.

**Comment by JuanjoSalvador** [comment] 2019-07-11 16:23
Hmmm... OK, it seems like a Mastodon related issue, not only for Tusky. But let me see...

**Comment by connyduck** [comment] 2019-07-11 17:21
Can reproduce the issue in Tusky 8.0, but not in our current master. Looks like it got fixed in https://github.com/tuskyapp/Tusky/pull/1351.

**Closed by connyduck** 2019-07-11 17:21 UTC

**Comment by Tak** [comment] 2019-07-11 18:27
Hm, it surprises me that that PR would have fixed it - but the bug also surprises me in the first place 🤷‍♂

**Comment by shegeman** [comment] 2019-07-21 21:52
Still seeing this on 8.1 . What version will I see the fix?

**Comment by connyduck** [comment] 2019-07-22 11:04
It works for me. Please provide a detailed bugreport (you can open a new issue) so I can investigate.
