### ISSUE TITLE
The toot's text content were hiding when insert 687th character in new toot!

### ISSUE THREAD

**Issue by ssmns** [tuskyapp/Tusky#1806] opened 2020-05-26 11:55 UTC
In my instance we allow inserting large toots (2048 character). But when I want to insert a large toot in Tusky after character 687, toot contents hiding (if remove some character the content go back) but when toot it, the toot has all text in timeline. 

* * * *
- Tusky Version:11.0
- Android Version:
- Android Device:Samsung A5 2017
- Mastodon instance (if applicable): mastodon.host

* if I write English character after 709 character the toot contents hided.

**Comment by charlag** [comment] 2020-05-26 15:00
Duplicate of #795

**Closed by charlag** 2020-05-26 15:00 UTC
Labels: duplicate
