### ISSUE TITLE
Option to Hide the Icons below Toots

### ISSUE THREAD

**Issue by ghost** [tuskyapp/Tusky#1869] opened 2020-07-31 06:30 UTC
Icons like Reply, Boost, Like etc. are always visible below every toot. An option to hide these a la Twidere would help the look the UI look more compact and sleek. User would then have to open a toot in order to interact with it. Most of the times we're just in view mode so. . . .

* * * *
- Tusky Version: 11.0
- Android Version: 10

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2023-01-28 13:47
Dupe of https://github.com/tuskyapp/Tusky/issues/1163

**Closed** 2023-05-11 14:49 UTC
