### ISSUE TITLE
Cropped preview

### ISSUE THREAD

**Issue by Thewisem** [tuskyapp/Tusky#2221] opened 2021-07-10 10:46 UTC
[Issue text goes here].

* * * *
- Tusky Version: 15.1
- Android Version: 7.1.1 Nougat
- Android Device: Samsung Galaxy Tab A
- Mastodon instance (if applicable): Fosstodon

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

There is a crop on the preview of the link I sent on mastodon when I send it
![Imagepipe_9](https://user-images.githubusercontent.com/74511929/125160382-31f56d80-e185-11eb-80c8-59e4382efe15.jpg)
This looks like a phone sized crop for a not phone sized tablet

**Comment by connyduck** [comment] 2022-03-13 17:11
Duplicate of https://github.com/tuskyapp/Tusky/issues/1995

**Closed by connyduck** 2022-03-13 17:11 UTC
