### ISSUE TITLE
Enhancement: Add filters

### ISSUE THREAD

**Issue by bannisdale** [tuskyapp/Tusky#784] opened 2018-08-20 17:09 UTC
The web view offers adding multiple filters. They can be added for a limited or unlimited amount of time.

The only thing I could find in Tusky is a single regex filter. I would love to be able to maintain the standard functionality in Tusky as well.

**Comment by connyduck** [comment] 2018-08-20 17:28
Duplicate of https://github.com/tuskyapp/Tusky/issues/740

**Closed by connyduck** 2018-08-20 17:28 UTC
