### ISSUE TITLE
[Feature request] Option to see boosts and favs in timeline

### ISSUE THREAD

**Issue by domenukk** [tuskyapp/Tusky#2761] opened 2022-11-06 12:28 UTC
Currently, only the amount of replies are visible before opening a message.
For me, the information how many people interacted with a toot is interesting metadata, and I don't want to click on everything just to see that.

I assume there should be plenty of space to display the number in the timeline, so I'd love to have this option added (unless it already exists and I didn't find it)
Thanks for a the work!

**Comment by connyduck** [comment] 2022-11-06 12:30
Duplicate of https://github.com/tuskyapp/Tusky/issues/2486

**Closed by connyduck** 2022-11-06 12:30 UTC

**Comment by domenukk** [comment] 2022-11-06 12:32
Sorry, didn't find it in the search 👍
