### ISSUE TITLE
Tablet scrolling problem

### ISSUE THREAD

**Issue by tagener-noisu** [tuskyapp/Tusky#4069] opened 2023-10-22 18:39 UTC
Timeline posts are centered on my tablet with empty space on the sides. I can't scroll the timeline by these empty spaces, only by the center part. It makes it a bit hard to scroll with one hand.
![Example with a random image from the net](https://github.com/tuskyapp/Tusky/assets/14823199/acb56538-8d8e-4f4a-b5aa-e79a3f643493)

* * * *
- Tusky Version: 23.0
- Android Version: 11
- Android Device: Tablet (2000x1200 resolution)

**Comment by connyduck** [comment] 2023-10-22 20:06
duplicate of https://github.com/tuskyapp/Tusky/issues/975

**Closed by connyduck** 2023-10-22 20:06 UTC
