### ISSUE TITLE
Inline images

### ISSUE THREAD

**Issue by cristilcal** [tuskyapp/Tusky#1504] opened 2019-09-28 19:20 UTC
Best mastodon app but still waiting inline images. So see full images of each toot on each timeçine without be required open each one thanks

* * * *
- Tusky Version: 9
- Android Version: 7.1.1
- Android Device: q6 plus
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2022-03-13 17:22
Duplicate of https://github.com/tuskyapp/Tusky/issues/1995

**Closed by connyduck** 2022-03-13 17:22 UTC
