### ISSUE TITLE
Display usernames as specified by webfinger redirects on servers set up with subdomains.

### ISSUE THREAD

**Issue by MaxxChatsko** [tuskyapp/Tusky#3861] opened 2023-07-18 02:26 UTC
On Mastodon, it's possible to set up a server on a subdomain such as you[at]mastodon.example.com, change the configuration settings, and have the server name and all usernames display the shortened you[at]example.com for a cleaner experience. This is done through webfinger redirects between LOCAL_DOMAIN and WEB_DOMAIN.

When Mastodon servers are set up this way, web applications of Mastodon adjust usernames accordingly, but Tusky doesn't yet realize the reconfigured settings from the webfinger redirect.

* * * *
- Tusky Version: 23.0

**Comment by nikclayton** [comment] 2023-07-18 13:20
Do you have an example account to use?

**Comment by MaxxChatsko** [comment] 2023-07-18 13:43
I didn't want to promote my account or server, but I'm maxx[at]mastodon.living.tech. This is shortened to maxx[at]living.tech on the web using the methods above, which will be true for all users on the server. Tusky doesn't yet realize the redirect and displays the former, longer username.

**Comment by nikclayton** [comment] 2023-07-19 06:58
Where are you seeing the longer user name?

In Tusky:

- If I search for "maxx@mastodon.living.tech" the search results list your account first, and the account is shown as `@maxx@living.tech`, which looks correct.
- If I click through to the account details page that also shows `@maxx@living.tech` under the name/profile photo

The account doesn't seem to have posted anything (that I can see from `@tusky@mastodon.social`) so I can't confirm what it looks like on a timeline.

**Comment by connyduck** [comment] 2023-07-25 17:21
Its about the username of the Tusky user which we display incorrectly.

Closing as duplicate of https://github.com/tuskyapp/Tusky/issues/688

**Closed by connyduck** 2023-07-25 17:21 UTC
