### ISSUE TITLE
Missing toots

### ISSUE THREAD

**Issue by Sisterratched** [tuskyapp/Tusky#3470] opened 2023-03-20 03:52 UTC
There are several toots per day missing from my Tusky timeline. They are all on the official Masto app. Seems completely random and includes mine and those of a random selection of people I follow. Why???

* * * *
- Tusky Version:
- Android Version:
- Android Device: samsung phone
- Mastodon instance (if applicable): toot.community

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2023-03-20 07:38
Duplicate of #3320

**Closed by Tak** 2023-03-20 07:38 UTC
