### ISSUE TITLE
[Feature Request] add image expand in timeline

### ISSUE THREAD

**Issue by FinecoFinit** [tuskyapp/Tusky#1853] opened 2020-07-03 11:20 UTC

**Comment by charlag** [comment] 2020-07-04 18:50
I'm sorry, could you provide at least some explanation? I have no idea what you are proposing. Thanks.

**Comment by WeFenFinit** [comment] 2020-07-05 16:00
@charlag In the news feed, all images are cropped, add the ability to disable cropping
Sorry for my English language

**Comment by charlag** [comment] 2020-07-18 10:20
I think we decided against uncropped images before.

**Comment by FinecoFinit** [comment] 2020-07-24 09:54
@charlag It's really uncomfortable tap and close every time to watch full picture. My timeline is filled only with them

**Comment by xGian18** [comment] 2020-09-26 04:34
Yeah I have a lot of cropped images too.
Can't u do a setting to let user chooses?

**Comment by charlag** [comment] 2022-05-10 20:36
Duplicate of #1995

**Closed by charlag** 2022-05-10 20:36 UTC
