### ISSUE TITLE
Quick switch accounts when composing a new message

### ISSUE THREAD

**Issue by HasHooves** [tuskyapp/Tusky#1396] opened 2019-07-16 06:33 UTC
A user should be able to tap the account icon to switch to another account when composing a message.

![Capture+_2019-07-15-23-27-54](https://user-images.githubusercontent.com/34425143/61271057-654cbf80-a758-11e9-900a-e4da76190abc.png)

* * * *
- Tusky Version: 8.1
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2019-07-16 17:16
Duplicate of https://github.com/tuskyapp/Tusky/issues/558

Yes, I would love this feature too, but unfortunately it is really difficult to implement, I already tried :(

**Closed by connyduck** 2019-07-16 17:16 UTC
