### ISSUE TITLE
[Feature Request] Threads for toots.

### ISSUE THREAD

**Issue by elephantchamp** [tuskyapp/Tusky#2968] opened 2022-12-02 02:44 UTC
I find this to be a problem when I make toots, I don't think this is even a thing yet but like. I want to be able to make threads before publishing my toot (This is something like twitter does) I don't want to reply underneath a comment of a post every single time just to make a long thread. It also spams the local feed of the instance you are in for other users and may be very annoying. You should be able to open the thread of the toot instead.

**Comment by connyduck** [comment] 2022-12-02 19:16
duplicate of https://github.com/tuskyapp/Tusky/issues/1425

**Closed by connyduck** 2022-12-02 19:16 UTC
