### ISSUE TITLE
Account disappearing

### ISSUE THREAD

**Issue by therealyez** [tuskyapp/Tusky#1264] opened 2019-05-17 22:49 UTC
[Bug].
I got multiple accounts, lately I've experienced that one of them suddenly disappear and I have to add it again. It's typically happening when I post to several accounts/switching between accounts. Suddenly I see one of my accounts twice when sharing a file from my phone, and at that point I know that an account is missing. Unfortunately it's randomly happening and I haven't been able to reproduce the bug but it's happening quite often. I think it has been going on for a couple of weeks. 

* * * *
- Tusky Version: 7.0
- Android Version: 9
- Android Device: Samsung Galaxy S8
- Mastodon instance (if applicable): humblr.social / sinblr.com

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2019-05-18 07:00
duplicate of https://github.com/tuskyapp/Tusky/issues/1185

**Closed by connyduck** 2019-05-18 07:00 UTC
Labels: duplicate

**Comment by therealyez** [comment] 2019-05-18 07:21
I saw the other instance but it's not quite a dublicate. This bug never happen using notifications but when posting with share function from device gallery. And as mentioned in #1185 this is not caused by rapidly changing account. I'm not even sure it is the same issue!

**Comment by connyduck** [comment] 2019-05-18 08:13
They may have different symptoms but I am pretty sure they have the same cause.

**Comment by therealyez** [comment] 2019-05-18 08:18
Okay, sorry then. I'm sure you know better than me
