### ISSUE TITLE
Post translation option in post menu.

### ISSUE THREAD

**Issue by TurekCom** [tuskyapp/Tusky#2823] opened 2022-11-13 20:03 UTC
Hello to you.
 It annoys me that when I browse posts on foreign servers, there is no option to translate the post in tusky itself.
 When I want to translate a post or read a local timeline that is in a different language, I have to open the chrome browser and select the translate to Polish option there.
 In Tusky, there could be an option to translate individual posts in the menu of each post, and there could be an option to translate all posts.  This would make it much easier to view mastodon in other languages ​​you don't understand.

Android 12
motorola edge 30 pro
tusky 19

**Comment by ShellWen** [comment] 2022-11-21 11:21
I need this feat too. As you can see my english is not good. 😭

**Comment by charlag** [comment] 2022-11-21 13:20
Please stop nagging, we are working on this in our free time. Contributions welcome, in any form.

**Comment by MinekPo1** [comment] 2022-11-21 14:38
Also note: as a temporary workaround, you can use the share content feature
to send the toot text to a translator app.

**Comment by MinekPo1** [comment] 2022-11-21 14:44
Also duplicate of #134

**Comment by jsoref** [comment] 2022-12-04 14:30
This is a duplicate of #134

**Comment by connyduck** [comment] 2024-03-09 15:35
https://github.com/tuskyapp/Tusky/pull/4307

**Closed by connyduck** 2024-03-09 15:35 UTC
