### ISSUE TITLE
Default emoticons disappeared after local emoticons were installed on the instance

### ISSUE THREAD

**Issue by cgubi** [tuskyapp/Tusky#1984] opened 2020-11-15 09:03 UTC
Mastodon instance: www.sociale.network
Tusky version: 12.1
Android Version: Android 10
Android Device: Samsung Galaxy A50

I am the admin of www.sociale.network and I just installed two custom emojis because Baby Yoda is toooooo cute :-)

![image](https://user-images.githubusercontent.com/10544025/99180655-5bf6ad00-2728-11eb-8899-790aaaa4ba70.png)

Nevertheless, when I connected with tusky client to my account on the instance, I see that only local emojis are accessible, and there is no way to see standard emojis.

![image](https://user-images.githubusercontent.com/10544025/99180795-b6dcd400-2729-11eb-9866-099f68ea6b61.png)

If I connect to another account that I have to another instance, then I see a different set of emojis.

My question is: Tusky is showing only the local emoticons of the instance to which you are connected? If so, it would be feasible to add a standard set of emojis to the client, or the only workaround to this is to extend the set of local emoticons? 

Thanks in advance.

**Comment by hex-m** [comment] 2022-04-29 10:52
This might be a duplicate of #1956. Tusky trusts that you have a keyboard installed that offers you a way to input default emojis. Only the custom ones from your instance are shown by Tusky itself.

**Closed** 2022-04-29 16:36 UTC
