### ISSUE TITLE
[Feature Request] Alt text reminder

### ISSUE THREAD

**Issue by dancapper** [tuskyapp/Tusky#2963] opened 2022-12-01 19:01 UTC
Option to remind users if they try to post an image without having added alt text.

This could operate similarly to the boost or fav confirmation, possibly taking the user directly to the alt text dialog if they select the appropriate option.

* * * *
- Tusky Version: 20.0
- Android Version:
- Android Device: 
- Mastodon instance (if applicable):

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2022-12-02 06:18
Duplicate of #2558

**Closed by Tak** 2022-12-02 06:18 UTC
