### ISSUE TITLE
Show Why a Post is In a Feed

### ISSUE THREAD

**Issue by TKK13909** [tuskyapp/Tusky#4792] opened 2024-12-06 05:11 UTC
### Pitch

There should be an indicator (different color, font, etc.) for why a post is in the current feed.

### Motivation

Many times I see a post and am completely confused as to why it's in my feed only to look through the hashtags and see one that I didn't even remember I was following. It would be nice to have a visual indicator for this.

**Comment by connyduck** [comment] 2024-12-06 06:30
Duplicate of https://github.com/tuskyapp/Tusky/issues/4173

**Closed by connyduck** 2024-12-06 06:30 UTC
Labels: enhancement
