### ISSUE TITLE
Show favourite and boost count on main feed

### ISSUE THREAD

**Issue by cunningdavid** [tuskyapp/Tusky#3110] opened 2022-12-27 22:50 UTC
It would be very helpful to show on the main feed how many favourites or boosts a toot has. Some other apps like "tooot" have this for example, as per the attached screenshot. Thank you.
![Screenshot_20221228_114555_tooot](https://user-images.githubusercontent.com/11324126/209732211-6e1731a5-7a63-4833-a9af-89dfdad5278d.jpg)

**Comment by Tak** [comment] 2022-12-28 06:50
Duplicate of #934

**Closed by Tak** 2022-12-28 06:50 UTC
