### ISSUE TITLE
Feature request: show toot language

### ISSUE THREAD

**Issue by raboof** [tuskyapp/Tusky#3096] opened 2022-12-23 08:51 UTC
I mainly toot in English, but am happy to see more content appearing on the Fediverse in my native language, Dutch.

To avoid annoying my non-Dutch followers, I'd like to only boost Dutch content that is correctly marked 'NL', so it can be filtered by non-Dutch speakers. Would it be possible to somehow show the toot language, even if it's hidden away somewhere?

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

(https://github.com/tuskyapp/Tusky/issues/135#issuecomment-456520616 suggests it is possible this information may not be available, though that would be somewhat silly and something to take upstream :) )

**Comment by Tak** [comment] 2022-12-23 18:14
Duplicate of #2989

**Comment by strk** [comment] 2023-11-25 14:54
> Duplicate of #2989

I think it may be good to keep this as it is more specific.
See also https://github.com/mastodon/mastodon/issues/28054

**Closed** 2024-01-03 20:17 UTC
