### ISSUE TITLE
Tusky unspecified "error" when viewing interactions

### ISSUE THREAD

**Issue by kenrestivo** [tuskyapp/Tusky#1830] opened 2020-06-13 07:17 UTC
When viewing interations ("notifications") tab in Tusky, I get:

![f3d0a4f7bff749538dd67fb1fd61b9b2b92d9cb27e4f72a44bb1b6fe9cd8134c](https://user-images.githubusercontent.com/108085/84562649-e61a8f80-ad0a-11ea-9d04-a90d852025d4.png)

* * * *
- Tusky Version: 11.0 F-droid
- Android Version:9
- Android Device:nextbit robin
- Mastodon instance (if applicable): hub.spaz.org

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

The server is Pleroma, and it pukes thusly:

```
Jun 13 06:50:29 spazlab mix[21384]: Request: GET /api/v1/notifications?limit=30&exclude_types%5B%5D=favourite&exclude_types%5B%5D=poll&exclude_types%5B%5D=reblog
Jun 13 06:50:29 spazlab mix[21384]: ** (exit) an exception was raised:
Jun 13 06:50:29 spazlab mix[21384]:     ** (Postgrex.Error) ERROR 22P02 (invalid_text_representation) invalid input value for enum notification_type: "poll"
Jun 13 06:50:29 spazlab mix[21384]:         (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
Jun 13 06:50:29 spazlab mix[21384]:         (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute/5
Jun 13 06:50:29 spazlab mix[21384]:         (ecto 3.4.4) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
Jun 13 06:50:29 spazlab mix[21384]:         (ecto 3.4.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
Jun 13 06:50:29 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/pagination.ex:40: Pleroma.Pagination.fetch_paginated/4
Jun 13 06:50:29 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/web/mastodon_api/controllers/notification_controller.ex:59: Pleroma.Web.MastodonAPI.NotificationController.index/2
Jun 13 06:50:29 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/web/mastodon_api/controllers/notification_controller.ex:5: Pleroma.Web.MastodonAPI.NotificationController.action/2
Jun 13 06:50:29 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/web/mastodon_api/controllers/notification_controller.ex:5: Pleroma.Web.MastodonAPI.NotificationController.phoenix_controller_pipeline/2
Jun 13 06:50:32 spazlab mix[21384]: 06:50:32.274 request_id=FhgHyfTnzxWPPZ0AByPR [error] Internal server error: %Postgrex.Error{connection_id: 21448, message: nil, postgres: %{code: :invalid_text_representation, file: "enum.c", line: "125", message: "invalid input value for enum notification_type: \"poll\"", pg_code: "22P02", routine: "enum_recv", severity: "ERROR", unknown: "ERROR"}, query: nil}
Jun 13 06:50:32 spazlab mix[21384]: 06:50:32.274 request_id=FhgHyfTnzxWPPZ0AByPR [info] Converted error Postgrex.Error to 500 response
Jun 13 06:50:32 spazlab mix[21384]: 06:50:32.278 [error] #PID<0.17174.3> running Pleroma.Web.Endpoint (connection #PID<0.17173.3>, stream id 1) terminated


Jun 13 06:50:32 spazlab mix[21384]: Request: GET /api/v1/notifications?limit=30&exclude_types%5B%5D=favourite&exclude_types%5B%5D=poll&exclude_types%5B%5D=reblog
Jun 13 06:50:32 spazlab mix[21384]: ** (exit) an exception was raised:
Jun 13 06:50:32 spazlab mix[21384]:     ** (Postgrex.Error) ERROR 22P02 (invalid_text_representation) invalid input value for enum notification_type: "poll"
Jun 13 06:50:32 spazlab mix[21384]:         (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
Jun 13 06:50:32 spazlab mix[21384]:         (ecto_sql 3.3.4) lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute/5
Jun 13 06:50:32 spazlab mix[21384]:         (ecto 3.4.4) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
Jun 13 06:50:32 spazlab mix[21384]:         (ecto 3.4.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
Jun 13 06:50:32 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/pagination.ex:40: Pleroma.Pagination.fetch_paginated/4
Jun 13 06:50:32 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/web/mastodon_api/controllers/notification_controller.ex:59: Pleroma.Web.MastodonAPI.NotificationController.index/2
Jun 13 06:50:32 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/web/mastodon_api/controllers/notification_controller.ex:5: Pleroma.Web.MastodonAPI.NotificationController.action/2
Jun 13 06:50:32 spazlab mix[21384]:         (pleroma 2.0.50-1459-g7aa6c829-develop) lib/pleroma/web/mastodon_api/controllers/notification_controller.ex:5: Pleroma.Web.MastodonAPI.NotificationController.phoenix_controller_pipeline/2
```

It would appear that  Tusky calling /api/v1/notifications?limit=30&exclude_types[]=favourite&exclude_types[]=poll&exclude_types[]=reblog is illegal.

The Pleroma frontend, however, only calls: 
/api/v1/notifications

Without all the extra junk, and it works.

**Comment by a1batross** [comment] 2020-06-13 07:54
Looks interesting. Happens for me as well.

It's triggered if user uncheck the "Polls" in notification filter. I guess because Pleroma really don't care about notifying user when poll is expired.

IMHO this should be addressed in [Pleroma GitLab](https://git.pleroma.social/pleroma/pleroma/issues/) too. 

So far, I think poll filter option should not appear on Pleroma and also Tusky should not hide the filter bar if an error is occured (I've sent similar patch but for "no notifications" case).

**Comment by connyduck** [comment] 2020-06-13 07:59
I can not reproduce on pleroma.fr or pleroma.site. Seems like they run older version of Pleroma though (?) so you might indeed get this fixed faster if you open a Pleroma issue as well. Introducing server version sniffing to Tusky is not a priority right now.

**Comment by a1batross** [comment] 2020-06-13 08:02
I guess they probably broke it after refactoring API. I'm running dev so... yeah, this should be reported. 

@kenrestivo the workaround for now is just uncheck "Show notification filter" in the app settings.

**Comment by charlag** [comment] 2020-06-13 08:14
I think it might be this commit which broke it:
https://git.pleroma.social/pleroma/pleroma/-/commit/40fc4e974e5f60c3d61702b17029566774898e84

**Comment by kenrestivo** [comment] 2020-06-13 20:34
Thanks, will move this to pleroma

**Closed** 2020-06-13 20:34 UTC
