### ISSUE TITLE
[Feature] Block entire Mastodon instance

### ISSUE THREAD

**Issue by heyitswither** [tuskyapp/Tusky#602] opened 2018-04-25 04:38 UTC
I'd rather not have to see toots from users of switter.at

**Comment by Lionirdeadman** [comment] 2018-04-25 07:26
@heyitswither, You can do that in the WebUI in case you didn't know.

(While you wait for this feature in Tusky)

**Comment by heyitswither** [comment] 2018-04-26 04:26
@Lionirdeadman how would I go about doing that?

**Comment by Lionirdeadman** [comment] 2018-04-26 05:45
@heyitswither,

Go to someone's profile from that instance, click on menu where you'd find mute and block then select "Hide everything from switter.at".

**Comment by charlag** [comment] 2018-05-05 14:24
So, it is controlled on the server side, right?

**Comment by Lionirdeadman** [comment] 2018-05-05 18:57
Yeah, it's server-side. Just like the muting and blocking features. 

There may or may not be an API request to do this though.

**Comment by charlag** [comment] 2018-05-05 19:01
I'm pretty sure there isn't (even if there is, it's not a priority). Thanks.

**Comment by Lionirdeadman** [comment] 2018-05-10 01:49
Actually, looks like that API exists.. [here](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#blocking-a-domain) therefore it should indeed be reopened until it's done.

**Comment by heyitswither** [comment] 2018-05-11 01:01
That is correct

**Comment by charlag** [comment] 2019-01-22 19:59
It's a duplicate of (much older) #301 so I'm closing this in favor of that issue.

**Closed** 2019-01-22 19:59 UTC
Labels: enhancement

**Comment by LostCreed** [comment] 2021-03-08 09:31
Hiding is not blocking.
