### ISSUE TITLE
Notification with null status crashes Tusky

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1584] opened 2019-12-13 19:48 UTC
So it seems that sometimes, the `/api/v1/notifications` endpoint does not fill the `status` field. In my case, it has been triggered by a double fav, i.e. someone faved a message, then unfaved it, then faved it again. Any refresh (time-based or manual) of the “Notifications” tab crashes Tusky.

On Mastodon web, it displays perfectly fine (it shows the message twice, because the fav existed and was linked to a status) — sorry for the blur, the bug happened with sensitive content:
![Screenshot_2019-12-13 Eldritch Café_blurred](https://user-images.githubusercontent.com/2446451/70825994-19c13f00-1de6-11ea-9bb8-9798ef189567.png)

After refreshing the page, Mastodon displays only one occurrence of the notification, so I’m under the assumption that Mastodon web can’t find the fav that has been deleted (even though it still exist in the notifications), and so can’t find the linked status, and in this case ignore notifications who can’t be linked to a status.

However, Tusky somehow didn’t ignore this kind of notification:
![Screenshot_20191213-201135_Tusky_cropped_blurred](https://user-images.githubusercontent.com/2446451/70825867-bf27e300-1de5-11ea-8cf9-8bf6aedb2f33.png)

I guess either it received a notification with a linked status then updated it after reading the endpoint another time, or it received the two notifications at once and displayed them as is. In both case, at some point Tusky tries to display a notification that doesn’t have a linked status (status: `null`) and some code in the update process crashes when encountering a `null` status.

I guess Tusky should ignore/remove these notifications, since it is the behavior of Mastodon web and it doesn’t make sense to display that someone faved a toot without being to display it underneath.

* * * *
- Tusky Version: 9.1 and 9.1-d0ce43df
- Android Version: 9
- Android Device: Oneplus 5
- Mastodon instance (if applicable): Eldritch.cafe (Mastodon 3.0.1)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

<details><summary>redacted JSON of the problematic notification</summary>
<p>

```json
{
      "id": "XXXXXX",
      "type": "favourite",
      "created_at": "2019-12-13T18:51:36.291Z",
      "account": {
        "id": "XXXXXX",
        "username": "xxxxxx",
        "acct": "xxxxxx@xxxxxx.xxx",
        "display_name": "xxxxxx",
        "locked": true,
        "bot": true,
        "created_at": "2018-12-17T23:17:46.168Z",
        "note": "xxxxxx",
        "url": "xxxxxx",
        "avatar": "xxxxxx",
        "avatar_static": "xxxxxx",
        "header": "xxxxxx",
        "header_static": "xxxxxx",
        "followers_count": XX,
        "following_count": XX,
        "statuses_count": XX,
        "last_status_at": "2019-12-13T18:52:21.063Z",
        "emojis": [],
        "fields": []
      },
      "status": null
    },
```
</p>
</details>

<details><summary>logcat</summary>
<p>

```
12-13 20:07:49.098  1592  1675 D OkHttp  : --> GET https://eldritch.cafe/api/v1/notifications?since_id=1988011&limit=30
12-13 20:07:49.223  1592  1675 D OkHttp  : <-- 200 https://eldritch.cafe/api/v1/notifications?since_id=1988011&limit=30 (124ms, unknown-length body)
12-13 20:07:49.269  1592  1592 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-13 20:07:49.349  1592  1592 I chatty  : uid=10270(com.keylesspalace.tusky.test) identical 2 lines
12-13 20:07:49.351  1592  1592 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-13 20:07:49.352  1592  1592 D AndroidRuntime: Shutting down VM
12-13 20:07:49.353  1592  1592 E AndroidRuntime: FATAL EXCEPTION: main
12-13 20:07:49.353  1592  1592 E AndroidRuntime: Process: com.keylesspalace.tusky.test, PID: 1592
12-13 20:07:49.353  1592  1592 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date com.keylesspalace.tusky.viewdata.StatusViewData$Concrete.getCreatedAt()' on a null object reference
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at com.keylesspalace.tusky.adapter.NotificationsAdapter.bindViewHolder(NotificationsAdapter.java:207)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at com.keylesspalace.tusky.adapter.NotificationsAdapter.onBindViewHolder(NotificationsAdapter.java:152)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1886)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:693)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-13 20:07:49.353  1592  1592 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</p>
</details>

**Comment by connyduck** [comment] 2019-12-24 12:29
Will try to fix, but this should be reported to Mastodon as well.

**Comment by connyduck** [comment] 2019-12-24 12:31
Duplicate of https://github.com/tuskyapp/Tusky/issues/1578

**Closed by connyduck** 2019-12-24 12:31 UTC
Labels: duplicate
