### ISSUE TITLE
Oversized context menu when editing image caption.

### ISSUE THREAD

**Issue by spazquest** [tuskyapp/Tusky#3770] opened 2023-06-23 02:06 UTC
Repro steps:
1. Compose a toot.
2. Upload media and select any image.
3. Select "Add Caption."
4. Long-press in the text field to bring up the context menu.
The context menu appears, with a background rectangle significantly larger than the menu contents. This partially covers up the text being entered.

I can repro consistently on Samsung Galaxy Tab A and Note 8, using the Samsung keyboard and Swype.

* * * *
- Tusky Version: 22.0
- Android Version: 9 ("One UI" version 1.0; kernel 4.4.153)
- Android Device: Galaxy Note (SM-N950U)
- Mastodon instance (if applicable):

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by spazquest** [comment] 2023-06-26 16:46
It won't let me screenshot in a text input, so here's a photograph of a tablet demonstrating the problem. I noticed just now that the rectangle is sometimes larger than others. (I don't know how to repro yet)
![20230622_183827](https://github.com/tuskyapp/Tusky/assets/577561/9aac328d-891d-4b28-a25b-340b9b866b05)

**Comment by Lakoja** [comment] 2023-06-27 19:29
(Duplicate of #3491, I researched this here: https://github.com/tuskyapp/Tusky/issues/3491#issuecomment-1510801902)

**Closed** 2023-07-07 13:10 UTC
