### ISSUE TITLE
Ability to translate discussions

### ISSUE THREAD

**Issue by Doesanythingwork** [tuskyapp/Tusky#2913] opened 2022-11-23 04:45 UTC
Tooot provides ability to translate discussions which enables other language users to join in the discourse. Trusty is the better App but missing the vital ability. 

Tooot seems to use server side translation tool or Google translate. Currently having to switch between Apps to join in.

* * * *
- Tusky Version: 19.0
- Android Version: 12
- Android Device: OnePlus 8T
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2022-11-25 07:52
Duplicate of #2823

**Closed by Tak** 2022-11-25 07:52 UTC
