### ISSUE TITLE
enable scrolling in the "void" next to timeline

### ISSUE THREAD

**Issue by ichier** [tuskyapp/Tusky#3337] opened 2023-02-18 20:10 UTC
I'm using a tablet horizontally, the timeline doesn't fill the whole width and is centered. It's nice, that swiping up and down in the "void" next to the timeline doesn't switch tabs anymore, while swiping left and right does. but swiping up and down next to the timeline should (of course?) scroll the timeline. that way your hand could rest without hiding the actual timeline, that would be much more convenient due to not moving your hand around. (you can't rest your hand on screen, since this would trigger buttons. like androids menu or tuskys compose button.)

* * * *
- Tusky Version: 21

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2023-02-19 15:20
Duplicate of https://github.com/tuskyapp/Tusky/issues/3033

**Closed by connyduck** 2023-02-19 15:20 UTC
