### ISSUE TITLE
Add selector for language of post

### ISSUE THREAD

**Issue by lukethelibrarian** [tuskyapp/Tusky#2885] opened 2022-11-20 22:55 UTC
For users who post in multiple languages, it would be helpful for the posting interface to include a switcher to set the language of the post when it differs from the default language set in preferences. This is possible in the Mastodon 4.0 web interface but not in Tusky; see ![lang-setting-mastodon](https://user-images.githubusercontent.com/29260386/202930951-25b60726-dd4f-48d3-afe1-cd20b57a41aa.png)

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Pixel 7
- Mastodon instance (if applicable): mastodon.world

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2022-11-20 23:09
It is already in beta

Duplicate of #2459

**Closed by charlag** 2022-11-20 23:09 UTC
