### ISSUE TITLE
Replies visible as public

### ISSUE THREAD

**Issue by steelman** [tuskyapp/Tusky#2798] opened 2022-11-09 22:35 UTC
### Steps  to reproduce:

Reply a publicly visible toot.

### What happens:

Visibility of the reply is set to "public"

### Expected result:

Visibility of the reply by default is set to "unlisted". User can change it.

* * * *
- Tusky Version: 19.0

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment] 2022-11-10 04:54
You can set your default post privacy in the account preferences. The default visibility of a reply will be the *least* visible of: the visibility of the status you're replying to, your default post privacy. So you can have the behavior you want by setting your default to unlisted.

**Comment by steelman** [comment] 2022-11-10 06:10
Yes, I've seen the setting. However, it doesn't do what I mean. Changing the setting influences also new original toots of mine and I want them to be *public*.

**Comment by evant** [comment] 2022-11-14 06:38
Idk if this is desired but I wanted this as well so I threw up a pr for it.

**Comment by steelman** [comment] 2022-11-14 17:52
Thanks. However, If I were a Tusky developer, I'd ask you to split the PR into two commits:

1. formatting changes,
2. new feature.

But that's just me.

**Comment by connyduck** [comment] 2022-11-14 17:57
I totally understand why one would want this, but I'm against implementing it without server support. "Default post privacy" syncs with the server, it is super weird to have a "default reply privacy" that does not. Once Mastodon adds this feature we can add it to Tusky as well.

**Comment by evant** [comment] 2022-11-14 19:10
Yeah agreed that it's weird. Will just keep it in my fork for now.

**Comment by fadookie** [comment] 2022-11-30 20:03
Thanks for the PR @evant , I might run your fork also. FYI the other Mastodon issue was closed as a duplicate of  https://github.com/mastodon/mastodon/issues/19685

**Comment by fadookie** [comment] 2023-06-01 00:38
I agree, who knows if the upstream feature request is ever going to be addressed, and even once it is it's going to take a while to roll out to all the mastodon servers on the fedi. I have been running my own locally-made build of tusky for 6 months specifically so I can have access to this feature, it's not ideal since I'm going to have to keep rebasing this branch whenever I want to pull in the latest new features. This is literally the only reason I'm not using mainline tusky builds now that edit-lists-from-profile has been merged.

**Comment by connyduck** [comment] 2024-05-15 18:18
Since Mastodon does not seem to have any interest in this feature, let's get it done in Tusky. @evant could you maybe resolve the merge conflicts?

**Comment by fadookie** [comment] 2024-05-24 05:37
If @evant isn't able to do this I can try at some point, this PR adds a db migration so in the past that's been the main source of conflicts (I haven't checked conflicts against latest main branch in a while though)

**Closed** 2024-06-09 18:25 UTC
