### ISSUE TITLE
Swiping between search categories clears the text box

### ISSUE THREAD

**Issue by mattedgar** [tuskyapp/Tusky#3650] opened 2023-05-14 08:05 UTC
Expected behaviour: text box content should be preserved when swiping between Posts, Accounts, and Hashtags

Actual behaviour:
![Screenshot_20230514-085236](https://github.com/tuskyapp/Tusky/assets/1483266/173d8ea9-01cb-409a-9278-1b02815fde0e)
Enter text in search box with default search category of "Posts"
Swipe to change to "Accounts"
![Screenshot_20230514-085247](https://github.com/tuskyapp/Tusky/assets/1483266/6c02fad2-3616-4eb2-88a8-61e6a2a561fe)
Search box is now empty 

* * * *
- Tusky Version: 22.0 beta 2
- Android Version: 12
- Android Device: Fairphone 4 5G
- Mastodon instance (if applicable):

- I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nikclayton** [comment] 2023-05-14 08:37
Duplicate of https://github.com/tuskyapp/Tusky/issues/3527

**Closed** 2023-05-14 08:37 UTC
