### ISSUE TITLE
[Troubleshooting] Cannot add any accounts

### ISSUE THREAD

**Issue by BenLubar** [tuskyapp/Tusky#1514] opened 2019-10-03 07:31 UTC
Trying to add an account results in an error message after clicking "Accept", one of:

- `An unidentified authorization error occurred.`
- `Failed getting a login token.`

How can I troubleshoot this? I have no existing data in Tusky.

* * * *
- Tusky Version: 9.1
- Android Version: 7.1.1
- Android Device: Chromebook (Edgar)
- Mastodon instance (if applicable): tried `mastodon.lubar.me`, `is.nota.live`, and `witches.live`

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2019-10-03 07:35
Duplicate of https://github.com/tuskyapp/Tusky/issues/792

**Closed by connyduck** 2019-10-03 07:35 UTC
