### ISSUE TITLE
Option to not mute notifications

### ISSUE THREAD

**Issue by BNolet** [tuskyapp/Tusky#1857] opened 2020-07-10 13:27 UTC
When on the mastodon web page you can mute folks and when you do, you get the option to not mute notifications from them. Can we get that option from Tusky too?

* * * *
- Tusky Version: 11.0
- Android Version: 10
- Android Device: Samsung Galaxy S10e
- Mastodon instance (if applicable): NA

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2020-07-16 21:30
This might be a duplicate of https://github.com/tuskyapp/Tusky/issues/1845 ?

**Comment by BNolet** [comment] 2020-07-17 17:29
It's not. I'm referring to this dialog present in the Mastodon web app not being present in Tusky:

![image](https://user-images.githubusercontent.com/10198484/87814282-6f087780-c831-11ea-8f66-4a88a770a618.png)

**Comment by connyduck** [comment] 2020-07-17 18:13
There is already a PR for it https://github.com/tuskyapp/Tusky/pull/1856

**Comment by BNolet** [comment] 2020-07-17 19:47
Sweet! Feel free to close when merged then :)

**Comment by BNolet** [comment] 2020-07-17 19:47
Sweet :) Looking forward to this being closed once merged

**Comment by connyduck** [comment] 2020-07-27 08:34
https://github.com/tuskyapp/Tusky/pull/1856

**Closed by connyduck** 2020-07-27 08:34 UTC
