### ISSUE TITLE
Maintain timeline position with phone orientation change

### ISSUE THREAD

**Issue by MoresoTorso** [tuskyapp/Tusky#1604] opened 2019-12-26 15:01 UTC
Good morning --

I'm a new Tusky user and have found, more by accident than practice, that when reading a timeline with my phone upright/portrait orientation, if I change that orientation to landscape, my position in the timeline goes right to the (reloaded) top/most recent post. 

In other words, changing my phone orientation reloads the timeline and puts me at the top rather than maintaining my position in the chronological posts. 

Any way that position can be maintained regardless of orientation changes? I've lost my place a few times just by nature of lying down with the phone and the timeline reloading and setting at the most recent post. 

Thanks for your consideration. 

* * * *
- Tusky Version: 9.1
- Android Version: 9
- Android Device: Samsung Galaxy S8
- Mastodon instance (if applicable):

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-12-28 19:29
Hi
I believe it's a duplicate of #1443

**Closed by charlag** 2019-12-28 19:29 UTC
