### ISSUE TITLE
Tusky doesn't properly keep timeline position

### ISSUE THREAD

**Issue by mhellwig** [tuskyapp/Tusky#1516] opened 2019-10-03 15:21 UTC
I use Tusky. I scroll along my timeline. I switch to another app, keep the phone in my pocket for a while, I re-open Tusky. Expectation: I see the same Toot that I saw when I had Tusky open the last time. Reality: I see some random other, newer Toot and have to scroll down and search until I find my position again. This works with other apps (e.g. fedilab, which I want to move away from for other reasons)

* * * *
- Tusky Version: 9.1
- Android Version: 8
- Android Device: Moto Z play
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2020-01-14 19:45
Duplicate of #1443

**Closed by charlag** 2020-01-14 19:45 UTC

**Comment by mhellwig** [comment] 2020-01-14 21:00
Please reopen, it is not a duplicate of the other issue. I have the phone orientation locked to portrait, so there is no orientation change, it just randomly happens on _some_ updates (but not all).

I have now experienced cases where the "jump to later position" happened while I was reading the timeline. I didn't even touch the screen, tusky did an automatic update of the timeline and Bam, 30 toots or so forward while I blinked. _definitely_ no orientation change while that happened.

**Comment by charlag** [comment] 2020-01-14 21:03
I linked wrong issue, sorry,
it's a duplicate of #89
