### ISSUE TITLE
UI states get lost on switching to another app

### ISSUE THREAD

**Issue by maxfragg** [tuskyapp/Tusky#4789] opened 2024-12-05 07:29 UTC
### Detailed description

Since August and still present in 26.2, when drafting a toot for example, switching to another app and returning, most of the time the draft is gone and I am back in the main timeline.
Drafts lost on that way also don't show up in the saved drafts.
Same applies to opened threads (even though, there the loss usually isn't that bad.

### Steps to reproduce the problem

1. Open thread, or compose toot/reply
2. Switch to another android app
3. Return to tusky, back in the timeline, opend toot or draft gone

### Debug information

Tusky 26.2

Device:

Google Pixel 6 
Android-Version: 15 
SDK-Version: 35

Account:

@mxk@hachyderm.io 
Version: 4.3.1

**Comment by Tak** [comment] 2024-12-05 08:10
Thanks, this is fixed by https://github.com/tuskyapp/Tusky/pull/4685 and will be available in the next release (or you could try a [nightly](https://tusky.app/faq/) build)

**Comment by connyduck** [comment] 2024-12-14 13:44
Yes it is. I can't reproduce it anymore. If you can please double check that you are on 27.0 beta 1 and provide additional information, like your Android, Device, and ideally a video of the issue.

**Comment by maxfragg** [comment] 2024-12-16 06:38
Just happened again with Beta 1 (same device as stated above!) - if I can provide any additional information, I would be glad to help.

**Comment by connyduck** [comment] 2024-12-17 18:39
I can reproduce it on certain circumstances even in 27 beta 1.
Funfact: The state is not lost, just covered by another instance of the main interface. Going back restores it.

**Closed** 2024-12-18 08:17 UTC
Labels: bug
