### ISSUE TITLE
New post text disappears after >1001 characters

### ISSUE THREAD

**Issue by pludi** [tuskyapp/Tusky#1603] opened 2019-12-24 10:29 UTC
The used instance allows for 500 character posts. Entering 1002 characters (character count shown as `-502`) has all text in the input field turn transparent (still selectable/editable, but not readable). Removing any characters to get to ≥-501 characters again has the text re-appear.

* * * *
- Tusky Version: 9.1
- Android Version: 8.1
- Android Device: bq Aquaris X Pro
- Mastodon instance (if applicable): chaos.social

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2019-12-24 12:16
Duplicate of #795

**Closed by connyduck** 2019-12-24 12:16 UTC
