### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by vanitasvitae** [tuskyapp/Tusky#1291] opened 2019-05-27 10:35 UTC
Hi!
First of all, great app! I love it!

Now the problem:
When I receive a notification on my desktop (using Halcyon) and acknowledge it (eg. by replying etc.) Tusky still receives a notification some minutes later. I'm not sure if this is a limitation of Mastodons protocol, but I expect Tusky to not prompt me with already read notifications.

Keep up the great work!

* * * *
- Tusky Version: 7.1
- Android Version: 8.1 (LineageOS)
- Android Device: Nexus 6p
- Mastodon instance (if applicable): fosstodon.org

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-05-27 17:28
Hey
There are two things here:
1. Tusky doesn't have realtime notifications because we avoid using non-free Google Play services. The only thing Android allows is checking every 15 minutes (roughly). There are hacks around this but we didn't even plan it properly yet.
2. There's nothing in Mastodon API, I believe, about seen/not seen notifications. We clear the list locally when you open notifications tab. 

Hopefully I'm wrong about the API but I think that Mastodon server doesn't keep track of this.

**Comment by vanitasvitae** [comment] 2019-05-27 18:02
> Tusky doesn't have realtime notifications because we avoid using non-free Google Play services. 

Of that I was aware and
>There's nothing in Mastodon API, I believe, about seen/not seen notifications.

that would be unfortuate.
Thank you for your answer :)

**Comment by connyduck** [comment] 2019-05-28 19:59
No, there is no way to do this with the Mastodon Api.
They have an open issue for this but it gets ignored since 2 years. https://github.com/tootsuite/mastodon/issues/4093

**Comment by vanitasvitae** [comment] 2019-05-28 20:53
Hm that's unfortunate :/
Nevertheless, thanks for the reply and for the awesome app :+1:

**Comment by charlag** [comment] 2019-12-04 20:48
Duplicate of #1542 (it's possible now I believe)

**Closed by charlag** 2019-12-04 20:48 UTC
