### ISSUE TITLE
Tusky crash on startup

### ISSUE THREAD

**Issue by JuanjoSalvador** [tuskyapp/Tusky#1141] opened 2019-03-21 15:34 UTC
I updated Tusky to 5.2 at the release day. I use Tusky everyday, no problems until today. Just launched it, and then it crashes.

Following the exception, it seems a polls' related problem. I mean, the exception is launched when trying to notify something, and my two last notifications of Mastodon are poll results notifications, maybe not included yet into Tusky (it's a pretty new feature of mastodon).

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.keylesspalace.tusky.entity.Notification$Type.ordinal()' on a null object reference
 at com.keylesspalace.tusky.a.o.c(SourceFile:181)
 at androidx.recyclerview.widget.RecyclerView$p.a(SourceFile:6026)
 at androidx.recyclerview.widget.RecyclerView$p.b(SourceFile:5958)
 at androidx.recyclerview.widget.LinearLayoutManager$c.a(SourceFile:11954)
 at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:1557)
 at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:1517)
 at androidx.recyclerview.widget.LinearLayoutManager.c(SourceFile:612)
 at androidx.recyclerview.widget.RecyclerView.D(SourceFile:3990)
 at androidx.recyclerview.widget.RecyclerView.y(SourceFile:3707)
 at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:4260)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SourceFile:625)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:1915)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at androidx.viewpager.widget.ViewPager.onLayout(SourceFile:1775)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.b(SourceFile:13193)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:899)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at androidx.drawerlayout.widget.DrawerLayout.onLayout(SourceFile:1231)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
 at android.view.View.layout(View.java:17666)
 at android.view.ViewGroup.layout(ViewGroup.java:5577)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2394)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2116)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1302)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6441)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
 at android.view.Choreographer.doCallbacks(Choreographer.java:688)
 at android.view.Choreographer.doFrame(Choreographer.java:623)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
 at android.os.Handler.handleCallback(Handler.java:754)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:163)
 at android.app.ActivityThread.main(ActivityThread.java:6238)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

* * * *
- Tusky Version: 5.2
- Android Version: 7.1.2 N2G47H (MIUI Global 10.2)
- Android Device: Xiaomi Redmi 4A
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2019-03-21 16:57
Hi
Yes, Mastodon have broken down backward compatibility. It is fixed in nightly but crashes in master now.
See #1123 
Duplicate of #1102

**Closed by charlag** 2019-03-21 16:57 UTC

**Comment by JuanjoSalvador** [comment] 2019-03-21 18:51
Nice, thanks for the info!
